### PR TITLE
Select MyEID applet with AID in myeid_init() to ensure that it is sel…

### LINKED ISSUE #1563: Failed to connect to card: Card is invalid or cannot be handled - Aventra MyEID
### Problem Description

A previously working MyEID smartcard suddenly returns the error "Card is invalid or cannot be handled".

### Proposed Resolution

Smartcard recognised successfully.

### Steps to reproduce

Most commands return the above error, including pkcs15-tool --dump.

The key line seems to be:

0x1124d55c0 02:14:30.828 [pkcs15-tool] card-myeid.c:171:myeid_init: Failed to get MyEID applet information.: -1210 (Card is invalid or cannot be handled)

This triggers opensc to keep looking for other drivers, even though this ATR matched.

### Logs

https://gist.github.com/minfrin/d16273b4772bc259d67799d2f7feb16a

### PR DESCRIPTION
**Pull request by hhonkanen**
…ected before sending other commands.

Fixes #1563 

Some other process might have selected Card Manager applet before using a MyEID card with OpenSC. In this case APDUs from OpenSC were routed to Card Manager instead of MyEID. Added code to select MyEID applet with AID right after ATR matching.

- [x] PKCS#11 module is tested

### CODE REVIEW

File: src/libopensc/card-myeid.c [hunk 1]
```diff
@@ -146,13 +146,44 @@ static int myeid_match_card(struct sc_card *card)
...
+	apdu.resp = apdu_resp;
+
+	rv = sc_transmit_apdu(card, &apdu);
+	LOG_TEST_RET(card->ctx, rv, "APDU transmit failed");
+	rv = sc_check_sw(card, apdu.sw1, apdu.sw2);
+	LOG_TEST_RET(card->ctx, rv, "Cannot select AID");
+
+	if (*out_len < apdu.resplen)
+		LOG_TEST_RET(card->ctx, SC_ERROR_BUFFER_TOO_SMALL, "Cannot select AID");
+	memcpy(out, apdu.resp, apdu.resplen);
```
Comment (frankmorgner) [inline src/libopensc/card-myeid.c]: why request response data when you don't need it?

Comment (hhonkanen) [reply src/libopensc/card-myeid.c]: I copied the code from the ias/ecc driver and just edited it a little. Didn't bother to remove the code that returns the response buffer, because SELECT AID command returns the FCI structure. We don't need it for now but actually some of the data in this structure might be useful in future development. I modified it a little to make the output buffer optional to avoid the unnecessary memcpy, new commit coming soon.

**Comment by dengert** [comment]
You said: "We don't need it for now".  There are problems with the Muscle and Coolkey applets that will return `9000` to any select SELECT command. If one of these cards is present. If you don't check the FCI for your AID your driver can get a false positive from one of these cards.  But if you next command is a MyEID only command it should catch it there. 
See #1483

**Comment by hhonkanen** [comment]
@dengert myeid_init() where this new SELECT AID command is executed is called after myeid_match_card(). Card matching is based entirely on ATR. The problem that we want to fix is that when we have already correctly found a MyEID card with myeid_match_card(), MyEID applet has got unselected. In this phase, if it is a MyEID card the new command selects MyEID applet on the cards. If for some reason we have got here with some other card than MyEID, the next command should fail anyway because it probably doesn't return the expected data. The next command is a GET DATA with MyEID specific parameters and requests applet information. But because Coolkey and Muscle have different ATRs, we shouldn't even get into this point with these cards.
