### PR TITLE
Fix TCOS IDKey support

### LINKED ISSUE #1869: TCOS: pkcs11-tool --login --test fails to sign
### Problem Description

OpenSC 0.20.0-rc3

```
$ pkcs11-tool --login --test
Using slot 0 with a present token (0x0)
Logging in to "IDKey Card".
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (IDKey1) 
error: PKCS11 function C_SignFinal failed: rv = CKR_DATA_INVALID (0x20)
Aborting.
```

### Logs

```
  testing key 0 (IDKey1)                                                                                                                       
P:14710; T:0x139761924822848 21:16:56.746 [opensc-pkcs11] framework-pkcs15.c:3675:pkcs15_prkey_get_attribute: pkcs15_prkey_get_attribute() called                                    
P:14710; T:0x139761924822848 21:16:56.746 [opensc-pkcs11] framework-pkcs15.c:3675:pkcs15_prkey_get_attribute: pkcs15_prkey_get_attribute() called      
P:14710; T:0x139761924822848 21:16:56.746 [opensc-pkcs11] mechanism.c:250:sc_pkcs11_sign_init: called                                                  
P:14710; T:0x139761924822848 21:16:56.746 [opensc-pkcs11] mechanism.c:256:sc_pkcs11_sign_init: mechanism 0x3, key-type 0x0                         
P:14710; T:0x139761924822848 21:16:56.746 [opensc-pkcs11] misc.c:268:session_start_operation: called                                               
P:14710; T:0x139761924822848 21:16:56.746 [opensc-pkcs11] misc.c:269:session_start_operation: Session 0x5570ec1c0a70, type 1                           
P:14710; T:0x139761924822848 21:16:56.746 [opensc-pkcs11] mechanism.c:376:sc_pkcs11_signature_init: called                                     
P:14710; T:0x139761924822848 21:16:56.746 [opensc-pkcs11] mechanism.c:430:sc_pkcs11_signature_init: returning with: 0 (Success)                                          
P:14710; T:0x139761924822848 21:16:56.746 [opensc-pkcs11] mechanism.c:283:sc_pkcs11_sign_init: returning with: 0 (Success)                       
P:14710; T:0x139761924822848 21:16:56.746 [opensc-pkcs11] pkcs11-object.c:679:C_SignInit: C_SignInit() = CKR_OK                                    
P:14710; T:0x139761924822848 21:16:56.747 [opensc-pkcs11] framework-pkcs15.c:3675:pkcs15_prkey_get_attribute: pkcs15_prkey_get_attribute() called  
P:14710; T:0x139761924822848 21:16:56.747 [opensc-pkcs11] pkcs11-object.c:263:C_GetAttributeValue: Object 93943485813376: CKA_ALWAYS_AUTHENTICATE = FALSE                   
P:14710; T:0x139761924822848 21:16:56.747 [opensc-pkcs11] pkcs11-object.c:285:C_GetAttributeValue: C_GetAttributeValue(hSession=0x5570ec1c0a70, hObject=0x5570ec19d280) = CKR_OK
P:14710; T:0x139761924822848 21:16:56.747 [opensc-pkcs11] mechanism.c:293:sc_pkcs11_sign_update: called                         
P:14710; T:0x139761924822848 21:16:56.747 [opensc-pkcs11] misc.c:290:session_get_operation: called                                         
P:14710; T:0x139761924822848 21:16:56.747 [opensc-pkcs11] mechanism.c:439:sc_pkcs11_signature_update: called                                     
P:14710; T:0x139761924822848 21:16:56.747 [opensc-pkcs11] mechanism.c:440:sc_pkcs11_signature_update: data part length 5                         
P:14710; T:0x139761924822848 21:16:56.747 [opensc-pkcs11] mechanism.c:452:sc_pkcs11_signature_update: returning with: 0 (Success)              
P:14710; T:0x139761924822848 21:16:56.747 [opensc-pkcs11] mechanism.c:309:sc_pkcs11_sign_update: returning with: 0 (Success)                   
P:14710; T:0x139761924822848 21:16:56.747 [opensc-pkcs11] pkcs11-object.c:749:C_SignUpdate: C_SignUpdate() = CKR_OK                                    
P:14710; T:0x139761924822848 21:16:56.747 [opensc-pkcs11] mechanism.c:293:sc_pkcs11_sign_update: called                                          
P:14710; T:0x139761924822848 21:16:56.747 [opensc-pkcs11] misc.c:290:session_get_operation: called                                                 
P:14710; T:0x139761924822848 21:16:56.747 [opensc-pkcs11] mechanism.c:439:sc_pkcs11_signature_update: called                                       
P:14710; T:0x139761924822848 21:16:56.748 [opensc-pkcs11] mechanism.c:440:sc_pkcs11_signature_update: data part length 10                          
P:14710; T:0x139761924822848 21:16:56.748 [opensc-pkcs11] mechanism.c:452:sc_pkcs11_signature_update: returning with: 0 (Success)                                             
P:14710; T:0x139761924822848 21:16:56.748 [opensc-pkcs11] mechanism.c:309:sc_pkcs11_sign_update: returning with: 0 (Success)    
P:14710; T:0x139761924822848 21:16:56.748 [opensc-pkcs11] pkcs11-object.c:749:C_SignUpdate: C_SignUpdate() = CKR_OK               
P:14710; T:0x139761924822848 21:16:56.748 [opensc-pkcs11] mechanism.c:293:sc_pkcs11_sign_update: called                                          
P:14710; T:0x139761924822848 21:16:56.748 [opensc-pkcs11] misc.c:290:session_get_operation: called                                               
P:14710; T:0x139761924822848 21:16:56.748 [opensc-pkcs11] mechanism.c:439:sc_pkcs11_signature_update: called                                           
P:14710; T:0x139761924822848 21:16:56.748 [opensc-pkcs11] mechanism.c:440:sc_pkcs11_signature_update: data part length 241                          
P:14710; T:0x139761924822848 21:16:56.748 [opensc-pkcs11] mechanism.c:452:sc_pkcs11_signature_update: returning with: 0 (Success)                                               
P:14710; T:0x139761924822848 21:16:56.748 [opensc-pkcs11] mechanism.c:309:sc_pkcs11_sign_update: returning with: 0 (Success)                     
P:14710; T:0x139761924822848 21:16:56.748 [opensc-pkcs11] pkcs11-object.c:749:C_SignUpdate: C_SignUpdate() = CKR_OK                                    
P:14710; T:0x139761924822848 21:16:56.748 [opensc-pkcs11] misc.c:290:session_get_operation: called                                                                              
P:14710; T:0x139761924822848 21:16:56.748 [opensc-pkcs11] framework-pkcs15.c:3675:pkcs15_prkey_get_attribute: pkcs15_prkey_get_attribute() called
P:14710; T:0x139761924822848 21:16:56.749 [opensc-pkcs11] framework-pkcs15.c:3675:pkcs15_prkey_get_attribute: pkcs15_prkey_get_attribute() called
P:14710; T:0x139761924822848 21:16:56.749 [opensc-pkcs11] mechanism.c:521:sc_pkcs11_signature_size: returning with: 0 (Success)                                                 
P:14710; T:0x139761924822848 21:16:56.749 [opensc-pkcs11] mechanism.c:361:sc_pkcs11_sign_size: returning with: 0 (Success)                                                                                
P:14710; T:0x139761924822848 21:16:56.749 [opensc-pkcs11] mechanism.c:319:sc_pkcs11_sign_final: called                                           
P:14710; T:0x139761924822848 21:16:56.749 [opensc-pkcs11] misc.c:290:session_get_operation: called                                                                              
P:14710; T:0x139761924822848 21:16:56.749 [opensc-pkcs11] mechanism.c:462:sc_pkcs11_signature_final: called                                            
P:14710; T:0x139761924822848 21:16:56.749 [opensc-pkcs11] framework-pkcs15.c:3919:pkcs15_prkey_sign: Initiating signing operation, mechanism 0x3.
P:14710; T:0x139761924822848 21:16:56.749 [opensc-pkcs11] card.c:473:sc_lock: called                                                                                            
P:14710; T:0x139761924822848 21:16:56.749 [opensc-pkcs11] reader-pcsc.c:652:pcsc_lock: called                                                    
P:14710; T:0x139761924822848 21:16:56.749 [opensc-pkcs11] card.c:513:sc_lock: returning with: 0 (Success)
P:14710; T:0x139761924822848 21:16:56.749 [opensc-pkcs11] framework-pkcs15.c:4050:pkcs15_prkey_sign: Selected flags 1. Now computing signature for 256 bytes. 1024 bytes reserved.
P:14710; T:0x139761924822848 21:16:56.749 [opensc-pkcs11] pkcs15-sec.c:565:sc_pkcs15_compute_signature: called
P:14710; T:0x139761924822848 21:16:56.749 [opensc-pkcs11] pkcs15-sec.c:613:sc_pkcs15_compute_signature: supported algorithm flags 0x103, private key usage 0x7
P:14710; T:0x139761924822848 21:16:56.749 [opensc-pkcs11] padding.c:470:sc_get_encoding_flags: called
P:14710; T:0x139761924822848 21:16:56.750 [opensc-pkcs11] padding.c:474:sc_get_encoding_flags: iFlags 0x1, card capabilities 0x103
P:14710; T:0x139761924822848 21:16:56.750 [opensc-pkcs11] padding.c:525:sc_get_encoding_flags: pad flags 0x0, secure algorithm flags 0x1
P:14710; T:0x139761924822848 21:16:56.750 [opensc-pkcs11] padding.c:526:sc_get_encoding_flags: returning with: 0 (Success)
P:14710; T:0x139761924822848 21:16:56.750 [opensc-pkcs11] pkcs15-sec.c:671:sc_pkcs15_compute_signature: DEE flags:0x00000001 alg_info->flags:0x00000103 pad:0x00000000 sec:0x00000001
P:14710; T:0x139761924822848 21:16:56.750 [opensc-pkcs11] card.c:473:sc_lock: called
P:14710; T:0x139761924822848 21:16:56.750 [opensc-pkcs11] card.c:513:sc_lock: returning with: 0 (Success)
P:14710; T:0x139761924822848 21:16:56.750 [opensc-pkcs11] pkcs15-sec.c:86:select_key_file: called
P:14710; T:0x139761924822848 21:16:56.750 [opensc-pkcs11] card.c:817:sc_select_file: called; type=2, path=df075349
P:14710; T:0x139761924822848 21:16:56.750 [opensc-pkcs11] apdu.c:546:sc_transmit_apdu: called
P:14710; T:0x139761924822848 21:16:56.751 [opensc-pkcs11] card.c:473:sc_lock: called
P:14710; T:0x139761924822848 21:16:56.751 [opensc-pkcs11] card.c:513:sc_lock: returning with: 0 (Success)
P:14710; T:0x139761924822848 21:16:56.751 [opensc-pkcs11] apdu.c:513:sc_transmit: called
P:14710; T:0x139761924822848 21:16:56.751 [opensc-pkcs11] apdu.c:363:sc_single_transmit: called
P:14710; T:0x139761924822848 21:16:56.751 [opensc-pkcs11] apdu.c:370:sc_single_transmit: CLA:0, INS:A4, P1:8, P2:C, data(4) 0x7ffc9bd57e90
P:14710; T:0x139761924822848 21:16:56.751 [opensc-pkcs11] reader-pcsc.c:297:pcsc_transmit: reader 'Identiv SCR3500 C Contact Reader [CCID Interface] (55591830603542) 00 00'
P:14710; T:0x139761924822848 21:16:56.751 [opensc-pkcs11] reader-pcsc.c:298:pcsc_transmit: 
Outgoing APDU (9 bytes):
00 A4 08 0C 04 DF 07 53 49 .......SI
P:14710; T:0x139761924822848 21:16:56.751 [opensc-pkcs11] reader-pcsc.c:216:pcsc_internal_transmit: called
P:14710; T:0x139761924822848 21:16:56.792 [opensc-pkcs11] reader-pcsc.c:307:pcsc_transmit: 
Incoming APDU (2 bytes):
90 00 ..
P:14710; T:0x139761924822848 21:16:56.792 [opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:14710; T:0x139761924822848 21:16:56.792 [opensc-pkcs11] apdu.c:535:sc_transmit: returning with: 0 (Success)
P:14710; T:0x139761924822848 21:16:56.792 [opensc-pkcs11] card.c:523:sc_unlock: called
P:14710; T:0x139761924822848 21:16:56.793 [opensc-pkcs11] card-tcos.c:397:tcos_select_file: returning with: 0 (Success)
P:14710; T:0x139761924822848 21:16:56.793 [opensc-pkcs11] card.c:852:sc_select_file: returning with: 0 (Success)
P:14710; T:0x139761924822848 21:16:56.793 [opensc-pkcs11] pkcs15-sec.c:123:select_key_file: returning with: 0 (Success)
P:14710; T:0x139761924822848 21:16:56.793 [opensc-pkcs11] sec.c:105:sc_set_security_env: called
P:14710; T:0x139761924822848 21:16:56.793 [opensc-pkcs11] card-tcos.c:499:tcos_set_security_env: Key-Reference 84 (len=1)
P:14710; T:0x139761924822848 21:16:56.793 [opensc-pkcs11] card-tcos.c:504:tcos_set_security_env: TCOS3:1 PKCS1:0
P:14710; T:0x139761924822848 21:16:56.793 [opensc-pkcs11] apdu.c:546:sc_transmit_apdu: called
P:14710; T:0x139761924822848 21:16:56.793 [opensc-pkcs11] card.c:473:sc_lock: called
P:14710; T:0x139761924822848 21:16:56.793 [opensc-pkcs11] card.c:513:sc_lock: returning with: 0 (Success)
P:14710; T:0x139761924822848 21:16:56.793 [opensc-pkcs11] apdu.c:513:sc_transmit: called
P:14710; T:0x139761924822848 21:16:56.793 [opensc-pkcs11] apdu.c:363:sc_single_transmit: called
P:14710; T:0x139761924822848 21:16:56.793 [opensc-pkcs11] apdu.c:370:sc_single_transmit: CLA:0, INS:22, P1:41, P2:B8, data(6) 0x7ffc9bd57ee0
P:14710; T:0x139761924822848 21:16:56.794 [opensc-pkcs11] reader-pcsc.c:297:pcsc_transmit: reader 'Identiv SCR3500 C Contact Reader [CCID Interface] (55591830603542) 00 00'
P:14710; T:0x139761924822848 21:16:56.794 [opensc-pkcs11] reader-pcsc.c:298:pcsc_transmit: 
Outgoing APDU (11 bytes):
00 22 41 B8 06 80 01 0A 84 01 84 ."A........
P:14710; T:0x139761924822848 21:16:56.794 [opensc-pkcs11] reader-pcsc.c:216:pcsc_internal_transmit: called
P:14710; T:0x139761924822848 21:16:56.833 [opensc-pkcs11] reader-pcsc.c:307:pcsc_transmit:
Incoming APDU (2 bytes):
6A 80 j.
P:2644; T:0x4391890368 15:47:08.487 [opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:2644; T:0x4391890368 15:47:08.487 [opensc-pkcs11] apdu.c:535:sc_transmit: returning with: 0 (Success)
P:2644; T:0x4391890368 15:47:08.487 [opensc-pkcs11] card.c:525:sc_unlock: called
P:2644; T:0x4391890368 15:47:08.487 [opensc-pkcs11] iso7816.c:128:iso7816_check_sw: Incorrect parameters in the data field
P:2644; T:0x4391890368 15:47:08.487 [opensc-pkcs11] card-tcos.c:532:tcos_set_security_env: returning with: -1205 (Incorrect parameters in APDU)
P:2644; T:0x4391890368 15:47:08.487 [opensc-pkcs11] sec.c:109:sc_set_security_env: returning with: -1205 (Incorrect parameters in APDU)
P:2644; T:0x4391890368 15:47:08.487 [opensc-pkcs11] card.c:525:sc_unlock: called
P:2644; T:0x4391890368 15:47:08.487 [opensc-pkcs11] pkcs15-sec.c:707:sc_pkcs15_compute_signature: use_key() failed: -1205 (Incorrect parameters in APDU)
P:2644; T:0x4391890368 15:47:08.487 [opensc-pkcs11] card.c:525:sc_unlock: called
P:2644; T:0x4391890368 15:47:08.487 [opensc-pkcs11] reader-pcsc.c:701:pcsc_unlock: called
P:2644; T:0x4391890368 15:47:08.487 [opensc-pkcs11] framework-pkcs15.c:4067:pkcs15_prkey_sign: Sign complete. Result -1205.
P:2644; T:0x4391890368 15:47:08.487 [opensc-pkcs11] misc.c:71:sc_to_cryptoki_error_common: libopensc return value: -1205 (Incorrect parameters in APDU)
P:2644; T:0x4391890368 15:47:08.487 [opensc-pkcs11] mechanism.c:478:sc_pkcs11_signature_final: returning with: 32
P:2644; T:0x4391890368 15:47:08.487 [opensc-pkcs11] mechanism.c:336:sc_pkcs11_sign_final: returning with: 32
P:2644; T:0x4391890368 15:47:08.487 [opensc-pkcs11] pkcs11-object.c:791:C_SignFinal: C_SignFinal() = CKR_DATA_INVALID
...
```

### PR DESCRIPTION
**Pull request by Jakuje**
Fixes #1869 

##### Checklist

- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [X] macOS tokend is tested

### CODE REVIEW

**Comment by jmastr** [comment]
Many thanks for help. Would be great to see the patch in v0.20.0-rc4?! :)

File: src/libopensc/card-tcos.c [hunk 1]
```diff
@@ -722,7 +723,6 @@ struct sc_card_driver * sc_get_tcos_driver(void)
 	tcos_ops.select_file          = tcos_select_file;
 	tcos_ops.list_files           = tcos_list_files;
 	tcos_ops.delete_file          = tcos_delete_file;
-	tcos_ops.set_security_env     = tcos_set_security_env;
```
Comment (frankmorgner) [inline src/libopensc/card-tcos.c]: did you delete the reference to `tcos_set_security_env` by accident? It is not used elsewhere...

Comment (frankmorgner) [reply src/libopensc/card-tcos.c]: I just saw that it's a duplicate, nevermind
