### PR TITLE
Issue 2105: Add new DNIe CA structure for the secure channel

### LINKED ISSUE #2105: DNIe 3.0 login fails with CKR_DATA_INVALID (0x20)
### Problem Description

I just got a fresh DNI 3.0 from the police station which works under Windows with the [_official_ software](https://www.dnielectronico.es/PortalDNIe/PRF1_Cons02.action?pag=REF_1104) but fails to login on MacOS 10.15.6 with OpenSC 0.20.0

Card reading seems to work just fine:

```
$ /Library/OpenSC/bin/opensc-tool -l
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Generic USB2.0-CRW
$ /Library/OpenSC/bin/opensc-tool -a
Using reader with a card: Generic USB2.0-CRW
3b:7f:96:00:00:00:6a:44:4e:49:65:20:01:01:55:04:21:03:90:00
$ /Library/OpenSC/bin/pkcs11-tool -L
Available slots:
Slot 0 (0x0): Generic USB2.0-CRW
  token label        : DNI electrónico (PIN1)
  token manufacturer : DGP-FNMT
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 020943f117350f
  pin min/max        : 4/16
$ /Library/OpenSC/bin/pkcs11-tool --test
Using slot 0 with a present token (0x0)
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signature: not a R/W session, skipping signature tests
Verify: not a R/W session, skipping verify tests
Decryption: not a R/W session, skipping decryption tests
No errors
```

But login doesn't:

```
$  /Library/OpenSC/bin/pkcs11-tool --login --test
Using slot 0 with a present token (0x0)
Logging in to "DNI electrónico (PIN1)".
Please enter User PIN: 
error: PKCS11 function C_Login failed: rv = CKR_DATA_INVALID (0x20)
Aborting.
```

It's worth noting that I haven't managed to get the [official DNI software to login under macOS](https://www.dnielectronico.es/PortalDNIe/PRF1_Cons02.action?pag=REF_1113) + Firefox (but I have no idea how to debug it).

### Proposed Resolution

Somehow get login to work :) . I am a coder myself, so I am happy to help but I am not familiar with OpenSC.

### Steps to reproduce

See above. I am using the default `opensc.conf` file at `/Library/OpenSC/etc/opensc.conf`

```
app default {
        # debug = 3;
        # debug_file = opensc-debug.txt;
        framework pkcs15 {
                # use_file_caching = true;
        }
}
```

### Logs

Relevant log excerpts seem to be:

```
$  /Library/OpenSC/bin/pkcs11-tool --login --test
[ ... ]

Using slot 0 with a present token (0x0)
P:35734; T:0x4692753856 04:02:11.347 [opensc-pkcs11] pkcs11-session.c:58:C_OpenSession: C_OpenSession(0x0)
P:35734; T:0x4692753856 04:02:11.347 [opensc-pkcs11] slot.c:452:slot_get_token: Slot(id=0x0): get token
P:35734; T:0x4692753856 04:02:11.347 [opensc-pkcs11] slot.c:470:slot_get_token: Slot-get-token returns OK
P:35734; T:0x4692753856 04:02:11.347 [opensc-pkcs11] pkcs11-session.c:94:C_OpenSession: C_OpenSession handle: 0x7ffe24c0cb90
P:35734; T:0x4692753856 04:22:11.347 [opensc-pkcs11] pkcs11-session.c:97:C_OpenSession: C_OpenSession() = CKR_OK
P:35734; T:0x4692753856 04:02:11.347 [opensc-pkcs11] framework-pkcs15.c:545:C_GetTokenInfo: C_GetTokenInfo(0)
P:35734; T:0x4692753856 04:22:11.347 [opensc-pkcs11] slot.c:452:slot_get_token: Slot(id=0x0): get token
P:35734; T:0x4692753856 04:02:11.347 [opensc-pkcs11] slot.c:470:slot_get_token: Slot-get-token returns OK
P:35734; T:0x4692753856 04:02:11.347 [opensc-pkcs11] framework-pkcs15.c:576:C_GetTokenInfo: C_GetTokenInfo() auth. object 0x7ffe25815c00, token-info flags 0x40D
P:35734; T:0x4692753856 04:02:11.347 [opensc-pkcs11] pkcs15-pin.c:695:sc_pkcs15_get_pin_info: called
P:35734; T:0x4692753856 04:02:11.348 [opensc-pkcs11] card.c:473:sc_lock: called
P:35734; T:0x4692753856 04:02:11.348 [opensc-pkcs11] reader-pcsc.c:657:pcsc_lock: called
P:35734; T:0x4692753856 04:02:11.348 [opensc-pkcs11] card.c:513:sc_lock: returning with: 0 (Success)
P:35734; T:0x4692753856 04:02:11.348 [opensc-pkcs11] sec.c:200:sc_pin_cmd: called
P:35734; T:0x4692753856 04:02:11.348 [opensc-pkcs11] card-dnie.c:2220:dnie_pin_cmd: called
P:35734; T:0x4692753856 04:02:11.348 [opensc-pkcs11] card-dnie.c:1828:dnie_card_ctl: called
P:35734; T:0x4692753856 04:02:11.348 [opensc-pkcs11] card-dnie.c:1848:dnie_card_ctl: returning with: 0 (Success)
P:35734; T:0x4692753856 04:02:11.348 [opensc-pkcs11] card-dnie.c:2264:dnie_pin_cmd: returning with: -1408 (Not supported)
P:35734; T:0x4692753856 04:02:11.348 [opensc-pkcs11] sec.c:247:sc_pin_cmd: returning with: -1408 (Not supported)
P:35734; T:0x4692753856 04:02:11.348 [opensc-pkcs11] card.c:523:sc_unlock: called
P:35734; T:0x4692753856 04:02:11.348 [opensc-pkcs11] reader-pcsc.c:709:pcsc_unlock: called
P:35734; T:0x4692753856 04:02:11.348 [opensc-pkcs11] pkcs15-pin.c:723:sc_pkcs15_get_pin_info: returning with: -1408 (Not supported)
P:35734; T:0x4692753856 04:02:11.348 [opensc-pkcs11] framework-pkcs15.c:594:C_GetTokenInfo: C_GetTokenInfo(0) returns CKR_OK
Logging in to "DNI electrónico (PIN1)".
Please enter User PIN: 

[ ... ]

P:3175; T:0x4495011264 04:02:58.077 [opensc-pkcs11] cwa14890.c:1157:cwa_create_secure_channel: Step 8.4.1.3: Send CVC IFD intermediate CA Cert for ICC verification
P:3175; T:0x4495011264 04:02:58.077 [opensc-pkcs11] cwa-dnie.c:469:dnie_get_cvc_ca_cert: called
P:3175; T:0x4495011264 04:02:58.077 [opensc-pkcs11] cwa-dnie.c:472:dnie_get_cvc_ca_cert: returning with: 0 (Success)
P:3175; T:0x4495011264 04:02:58.077 [opensc-pkcs11] cwa14890.c:406:cwa_verify_cvc_certificate: called
P:3175; T:0x4495011264 04:02:58.077 [opensc-pkcs11] apdu.c:546:sc_transmit_apdu: called
P:3175; T:0x4495011264 04:02:58.077 [opensc-pkcs11] card.c:473:sc_lock: called
P:3175; T:0x4495011264 04:02:58.077 [opensc-pkcs11] card.c:513:sc_lock: returning with: 0 (Success)
P:3175; T:0x4495011264 04:02:58.077 [opensc-pkcs11] apdu.c:513:sc_transmit: called
P:3175; T:0x4495011264 04:02:58.077 [opensc-pkcs11] apdu.c:363:sc_single_transmit: called
P:3175; T:0x4495011264 04:02:58.077 [opensc-pkcs11] apdu.c:370:sc_single_transmit: CLA:0, INS:2A, P1:0, P2:AE, data(210) 0x10a8a42d0
P:3175; T:0x4495011264 04:02:58.077 [opensc-pkcs11] reader-pcsc.c:297:pcsc_transmit: reader 'Generic USB2.0-CRW'
P:3175; T:0x4495011264 04:02:58.077 [opensc-pkcs11] reader-pcsc.c:298:pcsc_transmit: 
Outgoing APDU (215 bytes):
00 2A 00 AE D2 7F 21 81 CE 5F 37 81 80 3C BA DC .*.??.!.?_7..<??
36 84 BE F3 20 41 AD 15 50 89 25 8D FD 20 C6 91 6.?? A?.P.%.? ?.
15 D7 2F 9C 38 AA 99 AD 6C 1A ED FA B2 BF AC 90 .?/.8?.?l.?????.
92 FC 70 CC C0 0C AF 48 2A 4B E3 1A FD BD 3C BC .?p??.?H*K?.??<?
8C 83 82 CF 06 BC 07 19 BA AB B5 6B 6E C8 07 60 ...?.?..???kn?.`
A4 A9 3F A2 D7 C3 47 F3 44 27 F9 FF 5C 8D E6 D6 ??????G?D'??\.??
5D AC 95 F2 F1 9D AC 00 53 DF 11 A5 07 FB 62 5E ]?.??.?.S?.?.?b^
EB 8D A4 C0 29 9E 4A 21 12 AB 70 47 58 8B 8D 6D ?.??).J!.?pGX..m
A7 59 22 14 F2 DB A1 40 C7 D1 22 57 9B 5F 38 3D ?Y".?ۡ@??"W._8=
22 53 C8 B9 CB 5B C3 54 3A 55 66 0B DA 80 94 6A "Sȹ?[?T:Uf.?..j
FB 05 25 E8 E5 58 6B 4E 63 E8 92 41 49 78 36 D8 ?.%??XkNc?.AIx6?
D3 AB 08 8C D4 4C 21 4D 6A C8 56 E2 A0 07 F4 4F ӫ..?L!Mj?V?.?O
83 74 33 37 37 1A DD 8E 03 00 01 00 01 42 08 65 .t377.?......B.e
73 52 44 49 60 00 06                            sRDI`..
P:3175; T:0x4495011264 04:02:58.077 [opensc-pkcs11] reader-pcsc.c:216:pcsc_internal_transmit: called
P:3175; T:0x4495011264 04:02:58.101 [opensc-pkcs11] reader-pcsc.c:307:pcsc_transmit: 
Incoming APDU (2 bytes):
6A 80 j.
P:3175; T:0x4495011264 04:02:58.101 [opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:3175; T:0x4495011264 04:02:58.101 [opensc-pkcs11] apdu.c:535:sc_transmit: returning with: 0 (Success)
P:3175; T:0x4495011264 04:02:58.101 [opensc-pkcs11] card.c:523:sc_unlock: called
P:3175; T:0x4495011264 04:02:58.101 [opensc-pkcs11] card-dnie.c:1792:dnie_check_sw: called
P:3175; T:0x4495011264 04:02:58.101 [opensc-pkcs11] iso7816.c:128:iso7816_check_sw: Incorrect parameters in the data field
P:3175; T:0x4495011264 04:02:58.101 [opensc-pkcs11] card-dnie.c:1804:dnie_check_sw: returning with: -1205 (Incorrect parameters in APDU)
P:3175; T:0x4495011264 04:02:58.101 [opensc-pkcs11] cwa14890.c:418:cwa_verify_cvc_certificate: returning with: -1205 (Incorrect parameters in APDU)
P:3175; T:0x4495011264 04:02:58.101 [opensc-pkcs11] cwa14890.c:1349:cwa_create_secure_channel: Verify CVC CA failed
P:3175; T:0x4495011264 04:02:58.101 [opensc-pkcs11] cwa14890.c:1354:cwa_create_secure_channel: returning with: -1205 (Incorrect parameters in APDU)
P:3175; T:0x4495011264 04:02:58.101 [opensc-pkcs11] card-dnie.c:2159:dnie_pin_verify: Establish SM failed: -1205 (Incorrect parameters in APDU)
P:3175; T:0x4495011264 04:02:58.101 [opensc-pkcs11] card-dnie.c:2264:dnie_pin_cmd: returning with: -1205 (Incorrect parameters in APDU)
P:3175; T:0x4495011264 04:02:58.101 [opensc-pkcs11] sec.c:247:sc_pin_cmd: returning with: -1205 (Incorrect parameters in APDU)
P:3175; T:0x4495011264 04:02:58.101 [opensc-pkcs11] pkcs15-pin.c:455:sc_pkcs15_verify_pin_with_session_pin: PIN cmd result -1205
P:3175; T:0x4495011264 04:02:58.102 [opensc-pkcs11] card.c:523:sc_unlock: called
P:3175; T:0x4495011264 04:02:58.102 [opensc-pkcs11] reader-pcsc.c:709:pcsc_unlock: called
P:3175; T:0x4495011264 04:02:58.102 [opensc-pkcs11] pkcs15-pin.c:477:sc_pkcs15_verify_pin_with_session_pin: returning with: -1205 (Incorrect parameters in APDU)
P:3175; T:0x4495011264 04:02:58.102 [opensc-pkcs11] pkcs15-pin.c:333:sc_pkcs15_verify_pin: returning with: -1205 (Incorrect parameters in APDU)
P:3175; T:0x4495011264 04:02:58.102 [opensc-pkcs11] framework-pkcs15.c:1714:pkcs15_login: PKCS15 verify PIN returned -1205
P:3175; T:0x4495011264 04:02:58.102 [opensc-pkcs11] misc.c:71:sc_to_cryptoki_error_common: libopensc return value: -1205 (Incorrect parameters in APDU)
```

### PR DESCRIPTION
**Pull request by rickyepoderi**
Fixes #2105.

The police department in Spain (DGP) has changed the certificate structure for the secure channel recently. DNIe cards since serial number `BMP100001 ` (`IDESP` field in `dnie-tool -a`) are using new certs, keys and keys references to establish the secure channel. The new values for the new configuration have not been published by the DGP yet, they were discovered dumping and parsing the official binary distribution.

The two different configurations are now setup into a [configuration array](https://github.com/rickyepoderi/OpenSC/blob/dnie-2/src/libopensc/cwa-dnie.c#L417). The exact channel data to use is saved in [a new field inside the card private data](https://github.com/rickyepoderi/OpenSC/blob/dnie-2/src/libopensc/cwa-dnie.h#L91). And there are two new methods to assign and retrieve the channel data to use ([here](https://github.com/rickyepoderi/OpenSC/blob/dnie-2/src/libopensc/cwa-dnie.c#L608-L659)). As @2opremio suggested in the issue, the `dnie_set_channel_data` uses the `issuer` of the `icc_intermediate_ca_cert` to know which infrastructure the current card has to use. Please let me know if you agree with this idea or if you prefer another approach.

Don't merge it yet. We need to test this with different DNIe cards as I only have the new one. @miguel-cv please test with previous DNIe 3.0 and 2.0 if you can (maybe I have done a mistake copying all the data, it's a mess). But wait until the current PR is more or less accepted. I don't want you to work twice.

### CODE REVIEW

**Comment by 2opremio** [comment]
This is a great step forward, thanks!

On my Mac, with a new DNIe 3.0 (one week old),  it works, but not systematically (`login --login --test` fails about 50% of the time). 

I am using a [Coolbox card reader](https://coolbox.es/cajas-pc-y-componentes/2295-lector-de-tarjetas-externo-con-soporte-para-sim-y-dnie-cre-065-8437013799287.html?search_query=tarjeta&results=16):

```
$ tools/opensc-tool -a
Using reader with a card: Generic USB2.0-CRW
3b:7f:96:00:00:00:6a:44:4e:49:65:20:01:01:55:04:21:03:90:00
```

It sometimes fails with:

```
$  tools/pkcs11-tool --login --test
Using slot 0 with a present token (0x0)
Logging in to "DNI electrónico (PIN1)".
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  ERR: C_GenerateRandom(buf2,100) failed: CKR_GENERAL_ERROR (0x5)
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (KprivAutenticacion) 
error: PKCS11 function C_SignFinal failed: rv = CKR_GENERAL_ERROR (0x5)
Aborting.
```
<details><summary> DEBUG level 9 logs:</summary>
P:12499; T:0x4559961536 15:13:26.599 [opensc-pkcs11] reader-pcsc.c:324:pcsc_transmit: 
Outgoing APDU (18 bytes):
0C B0 00 00 0D 97 01 FF 8E 08 A8 10 47 E0 8D EA .?.....?..?.G?.?
12 A3                                           .?
P:12499; T:0x4559961536 15:13:26.599 [opensc-pkcs11] reader-pcsc.c:242:pcsc_internal_transmit: called
P:12499; T:0x4559961536 15:13:26.606 [opensc-pkcs11] reader-pcsc.c:333:pcsc_transmit: 
Incoming APDU (2 bytes):
61 00 a.
P:12499; T:0x4559961536 15:13:26.606 [opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:12499; T:0x4559961536 15:13:26.606 [opensc-pkcs11] apdu.c:426:sc_get_response: called
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] apdu.c:546:sc_transmit_apdu: called
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] card.c:473:sc_lock: called
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] card.c:513:sc_lock: returning with: 0 (Success)
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] apdu.c:513:sc_transmit: called
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] apdu.c:363:sc_single_transmit: called
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] apdu.c:370:sc_single_transmit: CLA:0, INS:C0, P1:0, P2:0, data(0) 0x0
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] sm.c:133:sc_sm_single_transmit: called
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] sm.c:134:sc_sm_single_transmit: SM_MODE:200
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] card-dnie.c:794:dnie_sm_get_wrapped_apdu: called
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] card-dnie.c:823:dnie_sm_get_wrapped_apdu: returning with: 0 (Success)
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] apdu.c:546:sc_transmit_apdu: called
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] card.c:473:sc_lock: called
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] card.c:513:sc_lock: returning with: 0 (Success)
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] apdu.c:513:sc_transmit: called
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] apdu.c:363:sc_single_transmit: called
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] apdu.c:370:sc_single_transmit: CLA:0, INS:C0, P1:0, P2:0, data(0) 0x0
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] reader-pcsc.c:323:pcsc_transmit: reader 'Generic USB2.0-CRW'
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] reader-pcsc.c:324:pcsc_transmit: 
Outgoing APDU (5 bytes):
00 C0 00 00 FF .?..?
P:12499; T:0x4559961536 15:13:26.607 [opensc-pkcs11] reader-pcsc.c:242:pcsc_internal_transmit: called
P:12499; T:0x4559961536 15:13:26.637 [opensc-pkcs11] reader-pcsc.c:271:pcsc_internal_transmit: Generic USB2.0-CRW:SCardTransmit/Control failed: 0x80100016
P:12499; T:0x4559961536 15:13:26.637 [opensc-pkcs11] reader-pcsc.c:472:pcsc_detect_card_presence: called
P:12499; T:0x4559961536 15:13:26.637 [opensc-pkcs11] reader-pcsc.c:360:refresh_attributes: Generic USB2.0-CRW check
P:12499; T:0x4559961536 15:13:26.638 [opensc-pkcs11] reader-pcsc.c:385:refresh_attributes: returning with: 0 (Success)
P:12499; T:0x4559961536 15:13:26.638 [opensc-pkcs11] reader-pcsc.c:477:pcsc_detect_card_presence: returning with: 5
P:12499; T:0x4559961536 15:13:26.638 [opensc-pkcs11] reader-pcsc.c:472:pcsc_detect_card_presence: called
P:12499; T:0x4559961536 15:13:26.638 [opensc-pkcs11] reader-pcsc.c:360:refresh_attributes: Generic USB2.0-CRW check
P:12499; T:0x4559961536 15:13:26.638 [opensc-pkcs11] reader-pcsc.c:385:refresh_attributes: returning with: 0 (Success)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] reader-pcsc.c:477:pcsc_detect_card_presence: returning with: 5
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] reader-pcsc.c:330:pcsc_transmit: unable to transmit
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] apdu.c:380:sc_single_transmit: unable to transmit APDU: -1107 (Transmit failed)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] apdu.c:516:sc_transmit: transmit APDU failed: -1107 (Transmit failed)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] card.c:523:sc_unlock: called
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] card-dnie.c:751:dnie_sm_free_wrapped_apdu: called
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] card-dnie.c:783:dnie_sm_free_wrapped_apdu: returning with: 0 (Success)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] sm.c:165:sc_sm_single_transmit: unable to transmit APDU: -1107 (Transmit failed)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] apdu.c:374:sc_single_transmit: returning with: -1107 (Transmit failed)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] apdu.c:516:sc_transmit: transmit APDU failed: -1107 (Transmit failed)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] card.c:523:sc_unlock: called
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] iso7816.c:766:iso7816_get_response: APDU transmit failed: -1107 (Transmit failed)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] apdu.c:463:sc_get_response: 
SM response data (256 bytes):
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] asn1.c:1679:asn1_decode: called, left=256, depth 0
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] apdu.c:467:sc_get_response: GET RESPONSE error: -1107 (Transmit failed)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] apdu.c:533:sc_transmit: cannot get all data with 'GET RESPONSE': -1107 (Transmit failed)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] card.c:523:sc_unlock: called
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] card-dnie.c:751:dnie_sm_free_wrapped_apdu: called
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] cwa14890.c:1607:cwa_decode_response: called
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] cwa14890.c:1612:cwa_decode_response: returning with: -1602 (Invalid secure messaging level)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] card-dnie.c:783:dnie_sm_free_wrapped_apdu: returning with: -1602 (Invalid secure messaging level)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] sm.c:165:sc_sm_single_transmit: unable to transmit APDU: -1107 (Transmit failed)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] apdu.c:374:sc_single_transmit: returning with: -1107 (Transmit failed)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] apdu.c:516:sc_transmit: transmit APDU failed: -1107 (Transmit failed)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] card.c:523:sc_unlock: called
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] card-dnie.c:1026:dnie_fill_cache: read_binary() APDU transmit failed
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] card-dnie.c:1027:dnie_fill_cache: returning with: -1107 (Transmit failed)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] card-dnie.c:1122:dnie_read_binary: Cannot fill cache. using iso_read_binary()
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] apdu.c:546:sc_transmit_apdu: called
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] card.c:473:sc_lock: called
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] card.c:513:sc_lock: returning with: 0 (Success)
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] apdu.c:513:sc_transmit: called
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] apdu.c:363:sc_single_transmit: called
P:12499; T:0x4559961536 15:13:26.639 [opensc-pkcs11] apdu.c:370:sc_single_transmit: CLA:0, INS:B0, P1:0, P2:0, data(0) 0x0
P:12499; T:0x4559961536 15:13:26.640 [opensc-pkcs11] reader-pcsc.c:323:pcsc_transmit: reader 'Generic USB2.0-CRW'
P:12499; T:0x4559961536 15:13:26.640 [opensc-pkcs11] reader-pcsc.c:324:pcsc_transmit: 
Outgoing APDU (5 bytes):
00 B0 00 00 FF .?..?
P:12499; T:0x4559961536 15:13:26.640 [opensc-pkcs11] reader-pcsc.c:242:pcsc_internal_transmit: called
P:12499; T:0x4559961536 15:13:26.646 [opensc-pkcs11] reader-pcsc.c:333:pcsc_transmit: 
Incoming APDU (2 bytes):
69 87 i.
P:12499; T:0x4559961536 15:13:26.646 [opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:12499; T:0x4559961536 15:13:26.646 [opensc-pkcs11] apdu.c:535:sc_transmit: returning with: 0 (Success)
P:12499; T:0x4559961536 15:13:26.646 [opensc-pkcs11] card.c:523:sc_unlock: called
P:12499; T:0x4559961536 15:13:26.646 [opensc-pkcs11] card-dnie.c:1777:dnie_check_sw: called
P:12499; T:0x4559961536 15:13:26.646 [opensc-pkcs11] card-dnie.c:1782:dnie_check_sw: Expected SM Data Object missing
P:12499; T:0x4559961536 15:13:26.646 [opensc-pkcs11] iso7816.c:162:iso7816_read_binary: Check SW error: -1600 (Generic Secure Messaging error)
P:12499; T:0x4559961536 15:13:26.646 [opensc-pkcs11] card.c:523:sc_unlock: called
P:12499; T:0x4559961536 15:13:26.646 [opensc-pkcs11] card.c:662:sc_read_binary: returning with: -1415 (EF offset too large)
P:12499; T:0x4559961536 15:13:26.646 [opensc-pkcs11] cwa-dnie.c:555:dnie_read_file: read_binary() failed
P:12499; T:0x4559961536 15:13:26.646 [opensc-pkcs11] cwa-dnie.c:556:dnie_read_file: returning with: -1200 (Card command failed)
P:12499; T:0x4559961536 15:13:26.646 [opensc-pkcs11] cwa-dnie.c:604:dnie_read_certificate: Cannot get intermediate CA cert
P:12499; T:0x4559961536 15:13:26.646 [opensc-pkcs11] cwa-dnie.c:605:dnie_read_certificate: returning with: -1200 (Card command failed)
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] cwa14890.c:1347:cwa_create_secure_channel: Cannot get ICC certificate from provider
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] cwa14890.c:1352:cwa_create_secure_channel: returning with: -1200 (Card command failed)
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] card-dnie.c:2184:dnie_pin_verify: returning with: -1200 (Card command failed)
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] card-dnie.c:2251:dnie_pin_cmd: returning with: -1200 (Card command failed)
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] sec.c:256:sc_pin_cmd: returning with: -1200 (Card command failed)
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] pkcs15-pin.c:455:sc_pkcs15_verify_pin_with_session_pin: PIN cmd result -1200
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] card.c:523:sc_unlock: called
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] reader-pcsc.c:736:pcsc_unlock: called
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] pkcs15-pin.c:477:sc_pkcs15_verify_pin_with_session_pin: returning with: -1200 (Card command failed)
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] pkcs15-pin.c:333:sc_pkcs15_verify_pin: returning with: -1200 (Card command failed)
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] framework-pkcs15.c:1714:pkcs15_login: PKCS15 verify PIN returned -1200
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] misc.c:71:sc_to_cryptoki_error_common: libopensc return value: -1200 (Card command failed)
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] pkcs11-session.c:322:C_Login: fLogin() rv 5
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] pkcs11-global.c:365:C_Finalize: C_Finalize()
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] ctx.c:906:sc_cancel: called
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] reader-pcsc.c:786:pcsc_cancel: called
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] slot.c:180:card_removed: Generic USB2.0-CRW: card removed
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] slot.c:481:slot_token_removed: slot_token_removed(0x0)
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] pkcs11-session.c:143:sc_pkcs11_close_all_sessions: real C_CloseAllSessions(0x0) 1
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] pkcs11-session.c:109:sc_pkcs11_close_session: real C_CloseSession(0x7feedbf06540)
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] framework-pkcs15.c:1575:pkcs15_release_token: pkcs15_release_token() not implemented
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] slot.c:481:slot_token_removed: slot_token_removed(0x1)
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] pkcs11-session.c:143:sc_pkcs11_close_all_sessions: real C_CloseAllSessions(0x1) 0
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] slot.c:481:slot_token_removed: slot_token_removed(0x2)
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] pkcs11-session.c:143:sc_pkcs11_close_all_sessions: real C_CloseAllSessions(0x2) 0
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] slot.c:481:slot_token_removed: slot_token_removed(0x3)
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] pkcs11-session.c:143:sc_pkcs11_close_all_sessions: real C_CloseAllSessions(0x3) 0
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] sc.c:335:sc_detect_card_presence: called
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] reader-pcsc.c:472:pcsc_detect_card_presence: called
P:12499; T:0x4559961536 15:13:26.647 [opensc-pkcs11] reader-pcsc.c:360:refresh_attributes: Generic USB2.0-CRW check
P:12499; T:0x4559961536 15:13:26.648 [opensc-pkcs11] reader-pcsc.c:385:refresh_attributes: returning with: 0 (Success)
P:12499; T:0x4559961536 15:13:26.648 [opensc-pkcs11] reader-pcsc.c:477:pcsc_detect_card_presence: returning with: 5
P:12499; T:0x4559961536 15:13:26.648 [opensc-pkcs11] sc.c:340:sc_detect_card_presence: returning with: 5
P:12499; T:0x4559961536 15:13:26.648 [opensc-pkcs11] pkcs15.c:1296:sc_pkcs15_unbind: called
P:12499; T:0x4559961536 15:13:26.648 [opensc-pkcs11] pkcs15-pin.c:863:sc_pkcs15_pincache_clear: called
P:12499; T:0x4559961536 15:13:26.648 [opensc-pkcs11] misc.c:71:sc_to_cryptoki_error_common: libopensc return value: 0 (Success)
P:12499; T:0x4559961536 15:13:26.648 [opensc-pkcs11] card.c:414:sc_disconnect_card: called
P:12499; T:0x4559961536 15:13:26.648 [opensc-pkcs11] card-dnie.c:895:dnie_finish: called
P:12499; T:0x4559961536 15:13:26.648 [opensc-pkcs11] cwa14890.c:1033:cwa_create_secure_channel: called
P:12499; T:0x4559961536 15:13:26.648 [opensc-pkcs11] cwa14890.c:1039:cwa_create_secure_channel: Setting CWA SM status to none
P:12499; T:0x4559961536 15:13:26.648 [opensc-pkcs11] cwa14890.c:1040:cwa_create_secure_channel: returning with: 0 (Success)
P:12499; T:0x4559961536 15:13:26.648 [opensc-pkcs11] card-dnie.c:901:dnie_finish: returning with: 0 (Success)
P:12499; T:0x4559961536 15:13:26.648 [opensc-pkcs11] reader-pcsc.c:669:pcsc_disconnect: Generic USB2.0-CRW:SCardDisconnect returned: 0x00000000
P:12499; T:0x4559961536 15:13:26.648 [opensc-pkcs11] card.c:436:sc_disconnect_card: returning with: 0 (Success)
P:12499; T:0x4559961536 15:13:26.649 [opensc-pkcs11] ctx.c:931:sc_release_context: called
P:12499; T:0x4559961536 15:13:26.649 [opensc-pkcs11] reader-pcsc.c:973:pcsc_finish: called
error: PKCS11 function C_Login failed: rv = CKR_GENERAL_ERROR (0x5)
</details>


Some other times, it fails with `error: PKCS11 function C_Sign failed: rv = CKR_USER_NOT_LOGGED_IN (0x101)`

<details><summary> DEBUG level 9 logs:</summary>
```
P:12368; T:0x4648930752 15:04:18.368 [opensc-pkcs11] sm.c:134:sc_sm_single_transmit: SM_MODE:200
P:12368; T:0x4648930752 15:04:18.368 [opensc-pkcs11] card-dnie.c:794:dnie_sm_get_wrapped_apdu: called
P:12368; T:0x4648930752 15:04:18.368 [opensc-pkcs11] card-dnie.c:823:dnie_sm_get_wrapped_apdu: returning with: 0 (Success)
P:12368; T:0x4648930752 15:04:18.368 [opensc-pkcs11] apdu.c:546:sc_transmit_apdu: called
P:12368; T:0x4648930752 15:04:18.369 [opensc-pkcs11] card.c:473:sc_lock: called
P:12368; T:0x4648930752 15:04:18.369 [opensc-pkcs11] card.c:513:sc_lock: returning with: 0 (Success)
P:12368; T:0x4648930752 15:04:18.369 [opensc-pkcs11] apdu.c:513:sc_transmit: called
P:12368; T:0x4648930752 15:04:18.369 [opensc-pkcs11] apdu.c:363:sc_single_transmit: called
P:12368; T:0x4648930752 15:04:18.369 [opensc-pkcs11] apdu.c:370:sc_single_transmit: CLA:0, INS:C0, P1:0, P2:0, data(0) 0x0
P:12368; T:0x4648930752 15:04:18.369 [opensc-pkcs11] reader-pcsc.c:323:pcsc_transmit: reader 'Generic USB2.0-CRW'
P:12368; T:0x4648930752 15:04:18.369 [opensc-pkcs11] reader-pcsc.c:324:pcsc_transmit: 
Outgoing APDU (5 bytes):
00 C0 00 00 FF .?..?
P:12368; T:0x4648930752 15:04:18.369 [opensc-pkcs11] reader-pcsc.c:242:pcsc_internal_transmit: called
P:12368; T:0x4648930752 15:04:18.390 [opensc-pkcs11] reader-pcsc.c:271:pcsc_internal_transmit: Generic USB2.0-CRW:SCardTransmit/Control failed: 0x80100016
P:12368; T:0x4648930752 15:04:18.390 [opensc-pkcs11] reader-pcsc.c:472:pcsc_detect_card_presence: called
P:12368; T:0x4648930752 15:04:18.390 [opensc-pkcs11] reader-pcsc.c:360:refresh_attributes: Generic USB2.0-CRW check
P:12368; T:0x4648930752 15:04:18.391 [opensc-pkcs11] reader-pcsc.c:385:refresh_attributes: returning with: 0 (Success)
P:12368; T:0x4648930752 15:04:18.391 [opensc-pkcs11] reader-pcsc.c:477:pcsc_detect_card_presence: returning with: 5
P:12368; T:0x4648930752 15:04:18.391 [opensc-pkcs11] reader-pcsc.c:472:pcsc_detect_card_presence: called
P:12368; T:0x4648930752 15:04:18.391 [opensc-pkcs11] reader-pcsc.c:360:refresh_attributes: Generic USB2.0-CRW check
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] reader-pcsc.c:385:refresh_attributes: returning with: 0 (Success)
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] reader-pcsc.c:477:pcsc_detect_card_presence: returning with: 5
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] reader-pcsc.c:330:pcsc_transmit: unable to transmit
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] apdu.c:380:sc_single_transmit: unable to transmit APDU: -1107 (Transmit failed)
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] apdu.c:516:sc_transmit: transmit APDU failed: -1107 (Transmit failed)
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] card.c:523:sc_unlock: called
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] card-dnie.c:751:dnie_sm_free_wrapped_apdu: called
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] card-dnie.c:783:dnie_sm_free_wrapped_apdu: returning with: 0 (Success)
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] sm.c:165:sc_sm_single_transmit: unable to transmit APDU: -1107 (Transmit failed)
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] apdu.c:374:sc_single_transmit: returning with: -1107 (Transmit failed)
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] apdu.c:516:sc_transmit: transmit APDU failed: -1107 (Transmit failed)
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] card.c:523:sc_unlock: called
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] iso7816.c:766:iso7816_get_response: APDU transmit failed: -1107 (Transmit failed)
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] apdu.c:463:sc_get_response: 
SM response data (256 bytes):
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] asn1.c:1679:asn1_decode: called, left=256, depth 0
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] apdu.c:467:sc_get_response: GET RESPONSE error: -1107 (Transmit failed)
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] apdu.c:533:sc_transmit: cannot get all data with 'GET RESPONSE': -1107 (Transmit failed)
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] card.c:523:sc_unlock: called
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] card-dnie.c:751:dnie_sm_free_wrapped_apdu: called
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] cwa14890.c:1607:cwa_decode_response: called
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] cwa14890.c:1612:cwa_decode_response: returning with: -1602 (Invalid secure messaging level)
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] card-dnie.c:783:dnie_sm_free_wrapped_apdu: returning with: -1602 (Invalid secure messaging level)
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] sm.c:165:sc_sm_single_transmit: unable to transmit APDU: -1107 (Transmit failed)
P:12368; T:0x4648930752 15:04:18.392 [opensc-pkcs11] apdu.c:374:sc_single_transmit: returning with: -1107 (Transmit failed)
P:12368; T:0x4648930752 15:04:18.393 [opensc-pkcs11] apdu.c:516:sc_transmit: transmit APDU failed: -1107 (Transmit failed)
P:12368; T:0x4648930752 15:04:18.393 [opensc-pkcs11] card.c:523:sc_unlock: called
P:12368; T:0x4648930752 15:04:18.393 [opensc-pkcs11] card-dnie.c:1026:dnie_fill_cache: read_binary() APDU transmit failed
P:12368; T:0x4648930752 15:04:18.393 [opensc-pkcs11] card-dnie.c:1027:dnie_fill_cache: returning with: -1107 (Transmit failed)
P:12368; T:0x4648930752 15:04:18.393 [opensc-pkcs11] card-dnie.c:1122:dnie_read_binary: Cannot fill cache. using iso_read_binary()
P:12368; T:0x4648930752 15:04:18.393 [opensc-pkcs11] apdu.c:546:sc_transmit_apdu: called
P:12368; T:0x4648930752 15:04:18.393 [opensc-pkcs11] card.c:473:sc_lock: called
P:12368; T:0x4648930752 15:04:18.393 [opensc-pkcs11] card.c:513:sc_lock: returning with: 0 (Success)
P:12368; T:0x4648930752 15:04:18.393 [opensc-pkcs11] apdu.c:513:sc_transmit: called
P:12368; T:0x4648930752 15:04:18.393 [opensc-pkcs11] apdu.c:363:sc_single_transmit: called
P:12368; T:0x4648930752 15:04:18.393 [opensc-pkcs11] apdu.c:370:sc_single_transmit: CLA:0, INS:B0, P1:0, P2:0, data(0) 0x0
P:12368; T:0x4648930752 15:04:18.393 [opensc-pkcs11] reader-pcsc.c:323:pcsc_transmit: reader 'Generic USB2.0-CRW'
P:12368; T:0x4648930752 15:04:18.393 [opensc-pkcs11] reader-pcsc.c:324:pcsc_transmit: 
Outgoing APDU (5 bytes):
00 B0 00 00 FF .?..?
P:12368; T:0x4648930752 15:04:18.393 [opensc-pkcs11] reader-pcsc.c:242:pcsc_internal_transmit: called
P:12368; T:0x4648930752 15:04:18.400 [opensc-pkcs11] reader-pcsc.c:333:pcsc_transmit: 
Incoming APDU (2 bytes):
69 87 i.
P:12368; T:0x4648930752 15:04:18.400 [opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:12368; T:0x4648930752 15:04:18.400 [opensc-pkcs11] apdu.c:535:sc_transmit: returning with: 0 (Success)
P:12368; T:0x4648930752 15:04:18.400 [opensc-pkcs11] card.c:523:sc_unlock: called
P:12368; T:0x4648930752 15:04:18.400 [opensc-pkcs11] card-dnie.c:1777:dnie_check_sw: called
P:12368; T:0x4648930752 15:04:18.400 [opensc-pkcs11] card-dnie.c:1782:dnie_check_sw: Expected SM Data Object missing
P:12368; T:0x4648930752 15:04:18.400 [opensc-pkcs11] iso7816.c:162:iso7816_read_binary: Check SW error: -1600 (Generic Secure Messaging error)
P:12368; T:0x4648930752 15:04:18.400 [opensc-pkcs11] card.c:523:sc_unlock: called
P:12368; T:0x4648930752 15:04:18.400 [opensc-pkcs11] card.c:662:sc_read_binary: returning with: -1415 (EF offset too large)
P:12368; T:0x4648930752 15:04:18.400 [opensc-pkcs11] cwa-dnie.c:555:dnie_read_file: read_binary() failed
P:12368; T:0x4648930752 15:04:18.400 [opensc-pkcs11] cwa-dnie.c:556:dnie_read_file: returning with: -1200 (Card command failed)
P:12368; T:0x4648930752 15:04:18.401 [opensc-pkcs11] cwa-dnie.c:604:dnie_read_certificate: Cannot get intermediate CA cert
P:12368; T:0x4648930752 15:04:18.401 [opensc-pkcs11] cwa-dnie.c:605:dnie_read_certificate: returning with: -1200 (Card command failed)
P:12368; T:0x4648930752 15:04:18.401 [opensc-pkcs11] cwa14890.c:1347:cwa_create_secure_channel: Cannot get ICC intermediate CA certificate from provider
P:12368; T:0x4648930752 15:04:18.401 [opensc-pkcs11] cwa14890.c:1352:cwa_create_secure_channel: returning with: -1200 (Card command failed)
P:12368; T:0x4648930752 15:04:18.401 [opensc-pkcs11] card-dnie.c:2144:dnie_pin_verify: Establish SM failed: -1200 (Card command failed)
P:12368; T:0x4648930752 15:04:18.401 [opensc-pkcs11] card-dnie.c:2251:dnie_pin_cmd: returning with: -1200 (Card command failed)
P:12368; T:0x4648930752 15:04:18.401 [opensc-pkcs11] sec.c:256:sc_pin_cmd: returning with: -1200 (Card command failed)
P:12368; T:0x4648930752 15:04:18.401 [opensc-pkcs11] pkcs15-pin.c:455:sc_pkcs15_verify_pin_with_session_pin: PIN cmd result -1200
P:12368; T:0x4648930752 15:04:18.401 [opensc-pkcs11] card.c:523:sc_unlock: called
P:12368; T:0x4648930752 15:04:18.401 [opensc-pkcs11] pkcs15-pin.c:477:sc_pkcs15_verify_pin_with_session_pin: returning with: -1200 (Card command failed)
P:12368; T:0x4648930752 15:04:18.401 [opensc-pkcs11] pkcs15-pin.c:851:sc_pkcs15_pincache_revalidate: Verify PIN error -1200
P:12368; T:0x4648930752 15:04:18.401 [opensc-pkcs11] card.c:523:sc_unlock: called
P:12368; T:0x4648930752 15:04:18.401 [opensc-pkcs11] pkcs15-sec.c:707:sc_pkcs15_compute_signature: use_key() failed: -1211 (Security status not satisfied)
P:12368; T:0x4648930752 15:04:18.401 [opensc-pkcs11] card.c:523:sc_unlock: called
P:12368; T:0x4648930752 15:04:18.401 [opensc-pkcs11] reader-pcsc.c:736:pcsc_unlock: called
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] framework-pkcs15.c:4067:pkcs15_prkey_sign: Sign complete. Result -1211.
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] misc.c:71:sc_to_cryptoki_error_common: libopensc return value: -1211 (Security status not satisfied)
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] mechanism.c:478:sc_pkcs11_signature_final: returning with: 257
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] mechanism.c:336:sc_pkcs11_sign_final: returning with: 257
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] pkcs11-object.c:727:C_Sign: C_Sign() = CKR_USER_NOT_LOGGED_IN
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] pkcs11-global.c:365:C_Finalize: C_Finalize()
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] ctx.c:906:sc_cancel: called
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] reader-pcsc.c:786:pcsc_cancel: called
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] slot.c:180:card_removed: Generic USB2.0-CRW: card removed
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] slot.c:481:slot_token_removed: slot_token_removed(0x0)
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] pkcs11-session.c:143:sc_pkcs11_close_all_sessions: real C_CloseAllSessions(0x0) 1
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] pkcs11-session.c:109:sc_pkcs11_close_session: real C_CloseSession(0x7fabb8d06860)
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] framework-pkcs15.c:1575:pkcs15_release_token: pkcs15_release_token() not implemented
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] slot.c:481:slot_token_removed: slot_token_removed(0x1)
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] pkcs11-session.c:143:sc_pkcs11_close_all_sessions: real C_CloseAllSessions(0x1) 0
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] slot.c:481:slot_token_removed: slot_token_removed(0x2)
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] pkcs11-session.c:143:sc_pkcs11_close_all_sessions: real C_CloseAllSessions(0x2) 0
P:12368; T:0x4648930752 15:04:18.402 [opensc-pkcs11] slot.c:481:slot_token_removed: slot_token_removed(0x3)
P:12368; T:0x4648930752 15:04:18.403 [opensc-pkcs11] pkcs11-session.c:143:sc_pkcs11_close_all_sessions: real C_CloseAllSessions(0x3) 0
P:12368; T:0x4648930752 15:04:18.403 [opensc-pkcs11] sc.c:335:sc_detect_card_presence: called
P:12368; T:0x4648930752 15:04:18.403 [opensc-pkcs11] reader-pcsc.c:472:pcsc_detect_card_presence: called
P:12368; T:0x4648930752 15:04:18.403 [opensc-pkcs11] reader-pcsc.c:360:refresh_attributes: Generic USB2.0-CRW check
P:12368; T:0x4648930752 15:04:18.404 [opensc-pkcs11] reader-pcsc.c:385:refresh_attributes: returning with: 0 (Success)
P:12368; T:0x4648930752 15:04:18.404 [opensc-pkcs11] reader-pcsc.c:477:pcsc_detect_card_presence: returning with: 5
P:12368; T:0x4648930752 15:04:18.404 [opensc-pkcs11] sc.c:340:sc_detect_card_presence: returning with: 5
P:12368; T:0x4648930752 15:04:18.404 [opensc-pkcs11] pkcs15.c:1296:sc_pkcs15_unbind: called
P:12368; T:0x4648930752 15:04:18.404 [opensc-pkcs11] pkcs15-pin.c:863:sc_pkcs15_pincache_clear: called
P:12368; T:0x4648930752 15:04:18.404 [opensc-pkcs11] misc.c:71:sc_to_cryptoki_error_common: libopensc return value: 0 (Success)
P:12368; T:0x4648930752 15:04:18.404 [opensc-pkcs11] card.c:414:sc_disconnect_card: called
P:12368; T:0x4648930752 15:04:18.404 [opensc-pkcs11] card-dnie.c:895:dnie_finish: called
P:12368; T:0x4648930752 15:04:18.404 [opensc-pkcs11] cwa14890.c:1033:cwa_create_secure_channel: called
P:12368; T:0x4648930752 15:04:18.404 [opensc-pkcs11] cwa14890.c:1039:cwa_create_secure_channel: Setting CWA SM status to none
P:12368; T:0x4648930752 15:04:18.404 [opensc-pkcs11] cwa14890.c:1040:cwa_create_secure_channel: returning with: 0 (Success)
P:12368; T:0x4648930752 15:04:18.404 [opensc-pkcs11] card-dnie.c:901:dnie_finish: returning with: 0 (Success)
P:12368; T:0x4648930752 15:04:18.404 [opensc-pkcs11] reader-pcsc.c:669:pcsc_disconnect: Generic USB2.0-CRW:SCardDisconnect returned: 0x00000000
P:12368; T:0x4648930752 15:04:18.405 [opensc-pkcs11] card.c:436:sc_disconnect_card: returning with: 0 (Success)
P:12368; T:0x4648930752 15:04:18.405 [opensc-pkcs11] ctx.c:931:sc_release_context: called
P:12368; T:0x4648930752 15:04:18.405 [opensc-pkcs11] reader-pcsc.c:973:pcsc_finish: called
error: PKCS11 function C_Sign failed: rv = CKR_USER_NOT_LOGGED_IN (0x101)
```
</details>

I am not sure the errors are related to this PR, I will try to find some time to investigate it later this week.

**Comment by miguel-cv** [comment]
Looks good to me, tried both 2.0 and 3.0 < BMP100001 

@2opremio Try with 
```
max_send_size = 65535;
max_recv_size = 65536;
```
in your opensc.conf
Before that, i got same error, but only with 3.0

**Comment by 2opremio** [comment]
@miguel-cv after chaging those settings the `CKR_GENERAL_ERROR (0x5)` problem went away, but I get `CKR_GENERAL_ERROR (0x5)` in almost every attempt.

**Comment by 2opremio** [comment]
@miguel-cv can you share your full configuration file?

**Comment by rickyepoderi** [comment]
@2opremio Also be sure to close any other app which has the pkcs11 configured and can interact with the card too (firefox, thunderbird,...). Sometime they conflict and it results in strange errors. But if you could login into the card I would say this fix is not related, the fix only changes the secure (pin and normal) channel creation.

**Comment by 2opremio** [comment]
>  But if you could login into the card I would say this fix is not related, the fix only changes the secure (pin and normal) channel creation.

Agreed, sorry for hijacking the PR (I would really want my DNIe to fully work :) )

**Comment by miguel-cv** [comment]
@2opremio 
[opensc.conf](https://pastebin.pl/view/raw/8d53ff97)
remove/insert the card between tries....

**Comment by 2opremio** [comment]
Thanks. That's identical to mine 😢

**Comment by dengert** [comment]
This is a read binary using Secure Messaging:
0C B0 00 00 0D 97 01 FF 8E 08 A8 10 47 E0 8D EA

It returns just the status 61 00, that says read  256 bytes using Get Response,
But the Get Response command 
00 C0 00 00 FF 
is requesting only 255. 
This then fails with:
Generic USB2.0-CRW:SCardTransmit/Control failed: 0x80100016
SCARD_E_NOT_TRANSACTED   ((LONG)0x80100016)   | An attempt was made to end a non-existent transaction.

This could be a locking problem, with an extra sc_unlock being called, or interference from other processes between the
sending of the read binary, and getting the response. i.e. the lock need to be held over both the read binary and get response,
or the set of ADPUs. 

It also looks like the reader is operation in Protocol T=0, rather then in T=1. This would explain why only the status was returned rather then the response data and the status.   Look for Protocol  T=X early in the debug log. 

Does this reader work with older DNie cards  or other cards? 
If it is new, it might not be supported by pcsc-lite.

**Comment by 2opremio** [comment]
It is at least 4 years old (it's one of the recommended readers for DNIe).

The reader works on Windows without problems.
GitHub <notifications@github.com> wrote:
“This is a read binary using Secure Messaging:
 0C B0 00 00 0D 97 01 FF 8E 08 A8 10 47 E0 8D EA

It returns just the status 61 00, that says read 256 bytes using Get Response,
 But the Get Response command
 00 C0 00 00 FF
 is requesting only 255.
 This then fails with:
 Generic USB2.0-CRW:SCardTransmit/Control failed: 0x80100016
 SCARD_E_NOT_TRANSACTED   ((LONG)0x80100016)   | An attempt was made to end a non-existent transaction.

This could be a locking problem, with an extra sc_unlock being called, or interference from other processes between the
 sending of the read binary, and getting the response. i.e. the lock need to be held over both the read binary and get response,
 or the set of ADPUs.

It also looks like the reader is operation in Protocol T=0, rather then in T=1. This would explain why only the status was returned rather then the response data and the status. Look for Protocol T=X early in the debug log.

Does this reader work with older DNie cards or other cards?
 If it is new, it might not be supported by pcsc-lite.”

**Comment by 2opremio** [comment]
@dengert would it help to get a debug log of a successful run?

I  trying to close everything which could be attempting read the card, but it doesn't work.

BTW, @rickyepoderi @miguel-cv did you manage to get Autofirma to work with this PR?

**Comment by miguel-cv** [comment]
@2opremio You're right. With Autofirma and firefox (at the same time) it doesn't work, Autofirma doesn't find certificates because card is locked:

```
P:2296; T:0x140358581249600 08:01:09.792 [onepin-opensc-pkcs11] reader-pcsc.c:628:pcsc_connect: Cherry GmbH SmartBoard XX44 [Smart Card Reader USB] 00 00:SCardConnect failed: 0x8010000b
P:2296; T:0x140358581249600 08:01:09.792 [onepin-opensc-pkcs11] card.c:403:sc_connect_card: returning with: -1116 (Reader in use by another application)
P:2296; T:0x140358581249600 08:01:09.792 [onepin-opensc-pkcs11] slot.c:259:card_detect: Cherry GmbH SmartBoard XX44 [Smart Card Reader USB] 00 00: SC connect card error -1116
P:2296; T:0x140358581249600 08:01:09.792 [onepin-opensc-pkcs11] misc.c:86:sc_to_cryptoki_error_common: libopensc return value: -1116 (Reader in use by another application)
P:2296; T:0x140358581249600 08:01:09.792 [onepin-opensc-pkcs11] pkcs11-global.c:582:C_GetSlotInfo: C_GetSlotInfo() card detect rv 0x30
P:2296; T:0x140358581249600 08:01:09.792 [onepin-opensc-pkcs11] pkcs11-global.c:599:C_GetSlotInfo: C_GetSlotInfo() flags 0x7FA7C7604B00
P:2296; T:0x140358581249600 08:01:09.792 [onepin-opensc-pkcs11] pkcs11-global.c:600:C_GetSlotInfo: C_GetSlotInfo(0x0) = CKR_DEVICE_ERROR
sep 15, 2020 8:01:09 AM es.gob.afirma.keystores.AOKeyStoreManagerHelperPkcs11 initPKCS11
ADVERTENCIA: Ha fallado el primer intento de inicializacion del PKCS#11 para la la biblioteca '/home/miguel/testopensc/ejecutables/lib/onepin-opensc-pkcs11.so', se reintentara: java.lang.reflect.InvocationTargetException
P:2296; T:0x140358581249600 08:01:09.793 [onepin-opensc-pkcs11] pkcs11-global.c:402:C_GetInfo: C_GetInfo()
Information for provider SunPKCS11-onepin-opensc-pkcs11_so
Library info:
  cryptokiVersion: 2.20
  manufacturerID: OpenSC Project                  
  flags: 0
  libraryDescription: OpenSC smartcard framework      
  libraryVersion: 0.20
```

...and the same if you open first Autofirma and then firefox:

```
P:1576; T:0x140039540766272 07:58:33.443 [onepin-opensc-pkcs11] reader-pcsc.c:628:pcsc_connect: Cherry GmbH SmartBoard XX44 [Smart Card Reader USB] 00 00:SCardConnect failed: 0x8010000b
P:1576; T:0x140039540766272 07:58:33.443 [onepin-opensc-pkcs11] card.c:403:sc_connect_card: returning with: -1116 (Reader in use by another application)
P:1576; T:0x140039540766272 07:58:33.443 [onepin-opensc-pkcs11] slot.c:259:card_detect: Cherry GmbH SmartBoard XX44 [Smart Card Reader USB] 00 00: SC connect card error -1116
P:1576; T:0x140039540766272 07:58:33.443 [onepin-opensc-pkcs11] misc.c:86:sc_to_cryptoki_error_common: libopensc return value: -1116 (Reader in use by another application)
```

It doesn't matter the max_send_size and max_recv_size.

**Comment by 2opremio** [comment]
@miguel-cv I was asking how you loaded the pkcs11 module on Autofirma (still interested).

Well, we can see it doesn't work. How can you use the DNIe without signing? Is there an alternative program?

**Comment by rickyepoderi** [comment]
@2opremio Is the previous branch https://github.com/rickyepoderi/OpenSC/tree/dnie working for you? (That one only changes the old value for the new ones, nothing more.)
@miguel-cv If you just use current OpenSC master (without this commit), is it the same? Or does it work for you? (You are using the old version, so master should be OK for you.)

Maybe I did something wrong but IMHO this commit is just changing the data for creating the secure channel and nothing more.

**Comment by miguel-cv** [comment]
Well, it just doesn't make sense to me...will test later today with master on my machine and in a clean vm, because i have other modules installed.

**Comment by 2opremio** [comment]
I managed to make it work on Autofirma (without experiencing the issues @miguel-cv mentions).

I still get errors with `pkcs11-tool --login --test` but I guess it's just a problem with the driver (@dengert should I create a separate issue for this?) and unrelated to this PR.

Thanks @rickyepoderi !

**Review by 2opremio — APPROVED** [review]

**Comment by dengert** [comment]
When an application connects to a card, it uses [ScardConnect](https://docs.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardconnecta) in one of 3 modes: SCARD_SHARE_SHARED, SCARD_SHARE_EXCLUSIVE or SCARD_SHARE_DIRECT. OpenSC normally uses SCARD_SHARE_SHARED, so other applications using SCARD_SHARE_SHARED can take turns. sc_lock when lock_count =0 will call pcsc to lock a transaction consisting or one or more APDUs. sc_unlock  decrements the lock_count, and if its 0, will release the pcsc lock. 

It looks like Autofirma is using SCARD_SHARE_EXCLUSIVE or SCARD_SHARE_DIRECT, so OpenSC can not connect to the card: 
"SCardConnect failed: 0x8010000b" "Reader in use by another application" So this is a problem Autofirma or the user has to address. 

In any  debug log, it is always helpful to have the line like these: 
- PC/SC options: connect_exclusive=0 disconnect_action=0 transaction_end_action=0 reconnect_action=0 enable_pinpad=1 enable_pace=1  (usually line 3 in the log. ) 
- pcsc_detect_readers ... SCardConnect(\<mode\>)
- part10_get_vendor_product: id_vendor=\<iv_v\> id_product=\<id_p\>
- pcsc_connect: Initial protocol: T=\<protocol\>
- sc_connect_card: card info name:'\<name\>', type:\<type\>, flags:\<flags\>, max_send/recv_size:\<int\>/\<int\>

A debug log of a working card old or new would help if it includes the above lines. 

It looks like the the failure is in card-dnie.c: dnie_fill_cache  but "Generic USB2.0-CRW:SCardTransmit/Control failed: 0x80100016"
looks strange. maybe a problem in the SM code with Protocol T=0? 

A debug log of a working card old or new would help if it includes the above lines.

**Comment by dengert** [comment]
Does Autofirma use OpenSC? 

The problems do not appear to be related to the current PR. 

It might be if some older application tries to establish a SM session using the wrong keys.  Note that using a card in Shared Mode, may cause one application to establish a SM sesion, which invalidates another applications session. The use of the use of the OpenSC  "card_reader_lock_obtained" which is called just after a pcsc lock for a session is obtained can be used to test if the SM is still valid.

**Comment by 2opremio** [comment]
> Does Autofirma use OpenSC?

It can (and in my case it does) since it tries to load the PKCS11 modules configured in Firefox if the native smart-card-reading-code fails (which it does for the new DNIe 3.0 cards, see https://github.com/ctt-gob-es/clienteafirma/issues/145 )

> The problems do not appear to be related to the current PR.

Agreed

> It might be if some older application tries to establish a SM session using the wrong keys. Note that using a card in Shared Mode, may cause one application to establish a SM sesion, which invalidates another applications session. The use of the use of the OpenSC "card_reader_lock_obtained" which is called just after a pcsc lock for a session is obtained can be used to test if the SM is still valid.

I doubt that's the case with my reader since I tried running `pkcs11-tool --login --test` while making sure everything else I suspect could be accessing the card is closed.

Anyways, I think this PR is fine. Question is whether I should be opening a separate issue or not.

**Comment by dengert** [comment]
That is up to you. I do not have a DNie card, (I  am in the US).

**Comment by miguel-cv** [comment]
Sorry, all is well, my mistake. My errors after first test are related to changing to:
`connect_exclusive = true;`
because i copied an old opensc.conf before testing with Autofirma....
Sorry again...

**Comment by 2opremio** [comment]
> That is up to you. I do not have a DNie card, (I am in the US).

Done #2110 

I think that (test-wise) this should be ready to merge.

**Comment by rickyepoderi** [comment]
I think the PR is ready for merging. Some different people have tested it and with several DNIe types and it's working for them. With my new DNie the test works OK (nothing special in the conf, as always), other people have reported it working too in the associated issue.

```bash
$ ./pkcs11-tool --login --test
Using slot 0 with a present token (0x0)
Logging in to "DNI electrónico (PIN1)".
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (KprivAutenticacion) 
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
  testing key 1 (KprivFirmaDigital) with 1 mechanism
    RSA-PKCS: OK
Verify (currently only for RSA)
  testing key 0 (KprivAutenticacion)
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
  testing key 1 (KprivFirmaDigital) with 1 mechanism
    RSA-PKCS: OK
Decryption (currently only for RSA)
  testing key 0 (KprivAutenticacion) -- can't be used to decrypt, skipping
  testing key 1 (KprivFirmaDigital) -- can't be used to decrypt, skipping
No errors
```

And, after some errors in the test itself, my [tester](https://github.com/rickyepoderi/dnie-pkcs11-tester) is working again too. So from my perspective this is OK to be merged. If you want something else just let me know.

**Comment by omula** [comment]
thanks @rickyepoderi I also tested it and works for me!

**Comment by alimoche** [comment]
it also works for me (tested with OpenSC 0.20.0 + https://github.com/OpenSC/OpenSC/pull/2109/commits/ec7da501001eb8238e70a36c85b87a33fba1323c + DNIe 3.0 after BMP100001) thanks a lot!

**Comment by gnusuari0** [comment]
Recompiled opensc-0.20.0 package from Ubuntu 20.04 LTS sources with this patch added. Login is working again.
If anyone is interested in Debian/Ubuntu packages you can get them from here: https://github.com/gnusuari0/blog/tree/packages_dnie3.0_bmp100001/packages/ubuntu/20.04/opensc-dnie

I also provide the debian directory to build on your computer from the source provided by Debian/Ubuntu. It's safer, as the packages are not signed.

**Comment by antomassol** [comment]
I've tested using this in libpam-pkcs11 login and it worked too. Tested with OpenSC 0.20.0 + ec7da50 + DNIe 3.0 after BMP100001 on Debian stable.

**Review by frankmorgner — COMMENTED** [review]
Thank you, overall this looks good.

But I have some comments regarding maintainability: I fear that when there is a third generation of cards, there will need to be yet another big commit adding hard coded certificates and parameters, which is suboptimal.

In [OpenPACE](https://github.com/frankmorgner/openpace), the only thing that's hard coded is a mapping from standardized domain parameters (some integer) to some elliptic curves. The parameters to use for the key establishment is read from EF.CardAccess/EF.CardSecurity from the card.

Also, with OpenPACE the root certificates for CAv2 (X.509) and for TAv2 (CVC) are directly taken from the official website and installed into a certain folder. If you want to support some other PKI, just put your certificates there.
In Windows builds of OpenSC, which include OpenPACE, this folder is found in `C:/Program Files/OpenSC Project/OpenSC/cvc`/`C:/Program Files/OpenSC Project/OpenSC/x509`. In Linux builds this path depends on the openpace installation.

Would it be possilbe to use this for your solution as well?

**Comment by frankmorgner** [comment]
OpenPACE is used in OpenSC in `src/sm/sm-eac.c`...

**Comment by 2opremio** [comment]
> Also, with OpenPACE the root certificates for CAv2 (X.509) and for TAv2 (CVC) are directly taken from the official website and installed into a certain folder.

The certificates are (sadly) not published anywhere by the Spanish Police. They were obtained through reverse engineering. 

Note that this is the first time this changes in 7 years since incorporating support for it in OpenSC (probably the first time in the life of DNIe).

**Comment by frankmorgner** [comment]
@rickyepoderi , would you agree to have a look if you could make adding new certs/params more flexible? This does not need to be now, but I'd like to have it when you need to add even more trust anchors...

**Comment by rickyepoderi** [comment]
@frankmorgner Sorry I'm very busy nowadays and I didn't have time to check the code til yesterday... More or less what you propose is the same than @gnusuari0 but just setting all the information just once (the user should change from one to the other conf). IMHO I prefer the current solution, I think this is a maintainability vs usability question. And considering the first DNIe was in 2006 I think the chances to have a new change in the short term are low.

But if you prefer to set all the channel information in the conf file we need the following:

- There are 3 public keys, 2 private keys, 3 cvc certificates (external files) and 8 general hexa fields (key references mostly, I would use something like "021f" hexa values directly in the conf for these fields). All these fields should be in the configuration to make DNIe work.
- The files cannot be downloaded from any place, so OpenSC should distribute them, in etc/dnie directory for example.
- The configuration would set by default one configuration (the old one for the moment) and the other would be in the conf commented out. If the user has a new DNIe he would need to change from the old to the new one. A more complicated configuration is possible with all the possible confs in the file, but I really wouldn't do this.

As I said I prefer the current solution because it just works for all the people without doing anything, and I think that the risk of a new change in the short term is low (taking in mind the first CA structure was in place for 14 years). But it's up to you, if you prefer the maintainability approach I'll try to do the changes in the following weeks (don't merge this if we are going to change, it's a quite different solution).

File: src/libopensc/cwa-dnie.c [hunk 1]
```diff
@@ -402,6 +605,59 @@ static int dnie_read_certificate(sc_card_t * card, char *certpath, X509 ** cert)
...
+ * @param icc_intermediate_ca_cert Pointer to the X509 icc intermediate CA certificate
+ * @return SC_SUCCESS if ok; else error code
+ */
+static int dnie_set_channel_data(sc_card_t * card, X509 * icc_intermediate_ca_cert) {
+	char *buf = NULL;
+	dnie_private_data_t *priv_data = GET_DNIE_PRIV_DATA(card);
+	LOG_FUNC_CALLED(card->ctx);
+
+	X509_NAME *issuer = X509_get_issuer_name(icc_intermediate_ca_cert);
+	buf = X509_NAME_oneline(issuer, buf, 0);
```
Comment (frankmorgner) [inline src/libopensc/cwa-dnie.c:644]: Please check if OpenSSL requires you to supply a valid issuer (i.e. != NULL)

**Review by frankmorgner — COMMENTED** [review]
Please don't get me wrong, I don't expect the user to configure anything. It should work out of the box (even with a blank opensc.conf). However, with the expiration of certificates we can expect new certificates in a couple of years. I think it would be easier to put a new CV cert/private key into some location rather than patching the code. Anyway, I am happy to accept the current solution if it works for the users.

While reviewing this code, I took a couple of minutes to review CWA 14890. It is a very simple key agreement scheme. And if I got it right, the security against eavesdropper is done by RSA-encrypting the nonces for key agreement for the opposite site (card/terminal both have signed certificates). And I think I have seen a security proof thereof. However, since the terminal's key is not stored securely (and now officially leaked), I have doubts that the proof still holds. Do you know if someone has looked at this issue?

**Comment by rickyepoderi** [comment]
>  However, since the terminal's key is not stored securely (and now officially leaked), I have doubts that the proof still holds. Do you know if someone has looked at this issue?

I really don't know the details behind the secure channel (I read the specification long ago and I didn't understand it completely, and now I remember almost nothing). But I don't think this is a leak in a proper sense. The DGP itself published the first terminal public/private key pair in the APDU [commands documentation](https://www.dnielectronico.es/PDFs/Manual_de_Comandos_para_Desarrolladores_102.pdf), chapter 7.2 - External data for the card. If you check the data there you see the old private key for the first version. Since v3.0 there is a new pin channel with a new terminal private key, that's why there are now two private keys, one for each channel. After that both private keys were added to several public projects as I commented before. And I suppose that now the same will happen in the near future with the new ones. We are just ahead of the rest now. In my understanding this private key is exactly the same as the {{st_key}} that, for example, npa cards use. I think that in PACE the idea is there are some readers that use an internal private key to do this, but I don't even know if DNIe can use those readers. I really don't know if the readers should coordinate with the card or what is needed here. You know much more than me about this for sure.

> Please check if OpenSSL requires you to supply a valid issuer (i.e. != NULL)

It just returns the internal pointer, no free needed. The certificate passed should be OK, because SC_SUCCESS was returned before calling the method. I'm going to check if NULL is returned although I think it will never happen. But better be sure. I'll update the PR in a few minutes.

File: src/libopensc/cwa-dnie.c (hunk 1 above)
Comment (rickyepoderi) [reply src/libopensc/cwa-dnie.c]: NULL is checked now just in case.

**Comment by frankmorgner** [comment]
Thanks for adding the check (errors happen all the time...)!

Let's continue the discussion of the protocol's security in https://github.com/OpenSC/OpenSC/issues/2120
