### PR TITLE
Set correct output length in PKCS#1 v1.5 depadding

### LINKED ISSUE #3076: Outlook not able to decrypt email - part 2
### Problem Description

When trying to decrypt an email in MS Outlook with OpenSC 0.25 I receive the following error message:

image

This seems to be related to https://github.com/OpenSC/OpenSC/issues/2925

### Proposed Resolution

Email should be decrypted

### Steps to reproduce

Decrypting an email

### Logs

https://gist.github.com/RufusJWB/c2ec57352395e7c7508dd6375622fb60

### PR DESCRIPTION
**Pull request by xhanulik**
Fixes #3076

The PKCS#1 v1.5 depadding function returned correctly the length of resulting message, but the `out_len` used in minidriver was not set to the length of the depadded message.

##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested

### CODE REVIEW

**Review by Jakuje — APPROVED** [review]
looks good. Lets see if it solves the originally reported issue.

**Comment by RufusJWB** [comment]
Sorry, but not working. Here are the logs: https://gist.github.com/RufusJWB/9d287f887f16c0e4732ab59a4f82bb0c

**Comment by xhanulik** [comment]
@RufusJWB thanks for report and log, I will investigate it along with the recent changes to minidriver.

**Comment by xhanulik** [comment]
I have found some additional issues

- the return value of depadding function should be non-negative in _good_ case
- the inversion after depadding is refactored, it should be touching only bytes from decrypted message now.

**Comment by RufusJWB** [comment]
I can confirm, the bug is fixed now.

**Comment by xhanulik** [comment]
@RufusJWB Thanks for testing!

File: src/minidriver/minidriver.c [hunk 1]
```diff
@@ -4710,7 +4710,7 @@ DWORD WINAPI CardRSADecrypt(__in PCARD_DATA pCardData,
 		goto err;
 	}
 
-	good = constant_time_eq_i(r, 0);
+	good = constant_time_ge(r, 0);
```
Comment (Jakuje) [inline src/minidriver/minidriver.c:4713]: https://github.com/OpenSC/OpenSC/issues/3085#issuecomment-2015236209

It was mentioned here, that zero length message does not make much sense so I would probably change this to `r > 0`.

**Review by Jakuje — COMMENTED** [review]
two minor comments.

As we are not Windows developers, is there somebody from you reporting this issue, able to put together some (ideally automated) tests of the minidriver to avoid such issues in the future? Or at least be able to run some manual tests before the release?

**Comment by RufusJWB** [comment]
> As we are not Windows developers, is there somebody from you reporting this issue, able to put together some (ideally automated) tests of the minidriver to avoid such issues in the future?

Sorry, but not me.

>Or at least be able to run some manual tests before the release?

Yes, I'd be happy to support. Ideally, you would provide a WinGet package with the pre-releases. I once opened an issue https://github.com/OpenSC/OpenSC/issues/2699 about this, which we might want to re-visit.

**Comment by Jakuje** [comment]
It looks like there is (outdated) opensc 0.23.0 as for today:

https://github.com/microsoft/winget-pkgs/blob/8f8f8792cd97da59cbf5da25d86f756cf00eebb2/manifests/o/OpenSC/OpenSC/0.23.0.0/OpenSC.OpenSC.yaml#L4

created after your request in microsoft/winget-pkgs#123939 so maybe just opening another to update would get it updated (or just opening a PR to update it) -- they just point out to our installers in github releases which do not look that complicated.

**Comment by RufusJWB** [comment]
> It looks like there is (outdated) opensc 0.23.0 as for today:
> 
> https://github.com/microsoft/winget-pkgs/blob/8f8f8792cd97da59cbf5da25d86f756cf00eebb2/manifests/o/OpenSC/OpenSC/0.23.0.0/OpenSC.OpenSC.yaml#L4
> 
> created after your request in [microsoft/winget-pkgs#123939](https://github.com/microsoft/winget-pkgs/issues/123939) so maybe just opening another to update would get it updated (or just opening a PR to update it) -- they just point out to our installers in github releases which do not look that complicated.

I wasn't aware, that this topic was picked up by someone at Microsoft. Great news. I'll follow up with them.

File: src/libopensc/padding.c [hunk 2]
```diff
@@ -154,13 +154,15 @@ sc_pkcs1_strip_02_padding_constant_time(sc_context_t *ctx, unsigned int n, const
...
 	unsigned int i = 0;
 	u8 *msg, *msg_orig = NULL;
-	unsigned int good, found_zero_byte, mask;
+	unsigned int good, found_zero_byte, mask, tmp_outlen;
 	unsigned int zero_index = 0, msg_index, mlen = -1, len = 0;
 	LOG_FUNC_CALLED(ctx);
 
-	if (data == NULL || data_len <= 0 || data_len > n || n < SC_PKCS1_PADDING_MIN_SIZE)
+	if (data == NULL || data_len <= 0 || data_len > n
+		|| n < SC_PKCS1_PADDING_MIN_SIZE || out_len == NULL)
```
Comment (Jakuje) [inline src/libopensc/padding.c:162]:
```suggestion
	if (data == NULL || data_len <= 0 || data_len > n ||
			n < SC_PKCS1_PADDING_MIN_SIZE || out_len == NULL)
```

**Review by Jakuje — APPROVED** [review]

**Comment by Jakuje** [comment]
Thank you!
