### PR TITLE
opensc-tool: do not use card driver to read ATR

### LINKED ISSUE #1606: "opensc-tool -a" not always prints ATR
Hi,

Symptom: "opensc-tool -a" is in some cases unable to print ATR

In default configuration "opensc-tool -a" prints correct ATR:
3b:be:18:00:00:41:05:10:00:00:00:00:00:00:00:00:00:90:00

If I configure some card driver to this ATR, several of card drivers prevent "opensc-tool -a" to print ATR (tested with drivers from src/libopensc/card-*.c):

atrust-acos: Segmentation fault
myeid: Failed to connect to card: Not allowed

authentic,belpic,cac,cac1,cardos,coolkey,epass2003,gemsafeV1,isoApplet,oberthur,openpgp:
Failed to connect to card: Card is invalid or cannot be handled

Of course, forcing some card driver to another card is not OK, but basic functionality of "opensc-tool -a" should not depend on card driver.

I do not have solution for this behavior, either "opensc-tool" is to be fixed, or lot of card drivers must be fixed or, this behavior is tolerable. 

(At minimum .. segfault in atrust-acos should be fixed).

### PR DESCRIPTION
**Pull request by popovec**
If card driver fails to connect to card, 'opensc-tool -a' may fail to print
ATR even if ATR is available from card reader.  Before use of card driver,
do only card reader connect, then print ATR.  Only if it is neccesary, use
card driver for the rest of opensc-tool functions.  Fixes #1606

### CODE REVIEW

File: src/tools/opensc-tool.c [hunk 1]
```diff
@@ -846,6 +847,22 @@ int main(int argc, char *argv[])
 			goto end;
 		action_count--;
 	}
+
+	err = util_connect_reader(ctx, &reader, opt_reader, opt_wait, verbose);
+	if (err)
+		goto end;
```
Comment (frankmorgner) [inline src/tools/opensc-tool.c]: please add the following:
```
		fprintf(stderr, "Failed to connect to reader: %s\n", sc_strerror(err));
		err = 1;

File: src/tools/util.c [hunk 2]
```diff
@@ -139,24 +137,36 @@ util_connect_card_ex(sc_context_t *ctx, sc_card_t **cardp,
...
-		if (sc_detect_card_presence(reader) <= 0) {
+		if (sc_detect_card_presence(*reader) <= 0) {
 			fprintf(stderr, "Card not present.\n");
 			return 3;
 		}
 	}
+	return 0;
+}
+int
+util_connect_card_ex(sc_context_t *ctx, sc_card_t **cardp,
```
Comment (martinpaljak) [inline src/tools/util.c]: This function is internal, why not change the signature and not make a new _ex ?

Comment (popovec) [reply src/tools/util.c]: The `util_connect_card_ex()`  is function with 6 arguments.  One specific argument is  `int do_lock`.  The `util_connect_card()` function is same as `util_connect_card_ex()` with `do_lock` set to 1.

There is 8 calls in whole opensc sources  to `util_connect_card_ex()` with `do_lock` set to  0,  and 9 calls to `util_connect_card()` (in 18 files).

IMHO, this PR should not change function `util_connect_card_ex ()` (because this introduces changes into files not affected by #1606).  If the `util_connect_card()` and `util_connect_card_ex ()` interface is not satisfactory, it should be solved in separate PR.
