### PR TITLE
[AuthentIC v3] Correctly handle APDUs with more than 256 bytes

### LINKED ISSUE #1147: Can't use DNIe from Perú
### Problem Description
I'm trying to integrate a card reader, but I can not get this firm, in theory I should support sha256 but throw me CKR_MECHANISM_INVALID
My smardcard reader is a bit4id minilector

### Steps to reproduce
pkcs11-tool  --module /Library/OpenSC/lib/pkcs11/opensc-pkcs11.so --login --pin 666666  --slot=02 -s -m SHA256-RSA-PKCS -i mytest -o sha256.out --verbose
Using signature algorithm SHA256-RSA-PKCS
error: PKCS11 function C_SignInit failed: rv = CKR_MECHANISM_INVALID (0x70)
### Logs
/Library/OpenSC/bin/pkcs11-tool --module /Library/OpenSC/lib/pkcs11/opensc-pkcs11.so -M
RESULT:
Supported mechanisms:
  SHA-1, digest
  SHA256, digest
  SHA384, digest
  SHA512, digest
  MD5, digest
  RIPEMD160, digest
  RSA-PKCS, keySize={1024,2048}, hw, decrypt, sign, verify
  SHA1-RSA-PKCS, keySize={1024,2048}, sign, verify
  SHA256-RSA-PKCS, keySize={1024,2048}, sign, verify
  RSA-PKCS-KEY-PAIR-GEN, keySize={1024,2048}, generate_key_pair

can someone help me ?, what am I doing wrong?

### PR DESCRIPTION
**Pull request by sergioag**
Multiple sc_transmit_apdu calls are made when more than 256 bytes (read) or 255 bytes (write and update) are requested.
This fixes #1147.

##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [x] Tested with the following card: Oberthur AuthentIC 3.2.2
	- [x] tested PKCS#11
	- [ ] tested Windows Minidriver
	- [x] tested macOS Tokend

### CODE REVIEW

**Comment by frankmorgner** [comment]
The special APDU handling in the authentic driver has been introduced by @viktorTarasov, it includes code specifically designed for a remote reader (not part of OpenSC) that sets the otherwise unused flag `SC_READER_HAS_WAITING_AREA`. We need his comment on how his use cases are reacting upon this change.

Note that the logic that you're removing with this PR is present in some more places in `card-authentic.c`. Those should be changed, too, if we decide to integrate this change.

**Comment by dengert** [comment]
@viktorTarasov, If the real problem is the card does not handle a READ_BINARY with Le=0, in T=0 mode,
would a solution like https://github.com/OpenSC/OpenSC/pull/1193 (i.e. max read is 255) also solve this problem?

What other cards/readers have this same issue with READ_BINARY? 

(It almost looks like a ambiguous issue in ISO7816-4 with with READ_BINARY. Does it return 9000 or 61xx)

**Comment by sergioag** [comment]
@frankmorgner I'm already testing the changes for authentic_update_binary and authentic_write_binary. I will update this PR with those changes as soon as I'm satisfied with them.

**Comment by sergioag** [comment]
@frankmorgner I have added the write and update changes. Should be ok now.

**Comment by frankmorgner** [comment]
@sergioag please update the description on the top accordingly.

Did you try to get in touch with @viktorTarasov?

**Comment by sergioag** [comment]
@frankmorgner I have updated the description. Hopefully it's better now. I also just sent out an email to Viktor.

**Comment by viktorTarasov** [comment]
@sergioag If it 'works for you', I do not have objections.

File: src/libopensc/card-authentic.c [hunk 1]
```diff
@@ -807,97 +807,53 @@ authentic_select_file(struct sc_card *card, const struct sc_path *path,
...
+		else
+			break;
 
 		idx += sz;
 		rest -= sz;
 	}
 
-	if (!apdus)   {
+	if (rv)   {
 		LOG_TEST_RET(ctx, SC_ERROR_INTERNAL, "authentic_read_binary() failed");
```
Comment (frankmorgner) [inline src/libopensc/card-authentic.c]: You are not `free()`ing `apdu` on error. What about using a local variable instead of allocating some memory?

File: src/libopensc/card-authentic.c [hunk 2]
```diff
@@ -917,37 +873,35 @@ authentic_write_binary(struct sc_card *card, unsigned int idx,
 	       "offs:%i,count:%"SC_FORMAT_LEN_SIZE_T"u,max_send_size:%"SC_FORMAT_LEN_SIZE_T"u",
 	       idx, count, card->max_send_size);
 
-	/* see comments for authentic_read_binary() */
-	sc_log(ctx, "reader flags 0x%lX", card->reader->flags);
-	if (count > 255 && !(card->reader->flags & SC_READER_HAS_WAITING_AREA))
-		LOG_TEST_RET(ctx, SC_ERROR_INVALID_DATA, "Invalid size of the data to read");
+	apdu = calloc(1, sizeof(struct sc_apdu));
+	if(!apdu)
+		LOG_TEST_RET(ctx, SC_ERROR_OUT_OF_MEMORY, "cannot allocate APDU");
```
Comment (frankmorgner) [inline src/libopensc/card-authentic.c]: same here, if you use a local variable, you're saving the hassle of cleaning up the memory.

**Comment by frankmorgner** [comment]
Thanks for the feedback, @viktorTarasov!

**Comment by frankmorgner** [comment]
@sergioag the implementation in `card-authentic.c` looks like the same as in `iso7816.c` now (minus some additional error checks that the ISO driver performs). Please check if you can remove the implementation for authentic by directly calling the implementation of the ISO driver.

File: src/libopensc/card-authentic.c (hunk 1 above)
Comment (sergioag) [reply src/libopensc/card-authentic.c]: Done. Much simpler now.

**Comment by sergioag** [comment]
@frankmorgner the iso7816.c implementation appears to use extended apdus, which don't appear to work on my card. It always returns invalid size.

File: src/libopensc/card-authentic.c (hunk 2 above)
Comment (sergioag) [reply src/libopensc/card-authentic.c]: Also done.

**Comment by frankmorgner** [comment]
you could try something like:
```
size_t max_recv_size = card->max_recv_size;
rv = iso_ops->read_binary(card, idx, buf, count, flags);
card->max_recv_size = max_recv_size;
```

**Comment by frankmorgner** [comment]
you could try something like:
```
size_t max_recv_size = card->max_recv_size;
card->max_recv_size = AUTHENTIC_READ_BINARY_LENGTH_MAX;
rv = iso_ops->read_binary(card, idx, buf, count, flags);
card->max_recv_size = max_recv_size;
```

**Comment by frankmorgner** [comment]
@sergioag did you have a look at the suggestion above?

**Comment by frankmorgner** [comment]
@sergioag, preparing a new release, could you look at the suggestion above?

**Comment by sergioag** [comment]
@frankmorgner Will do it tonight or tomorrow.

**Comment by frankmorgner** [comment]
thanks

**Comment by sergioag** [comment]
Still working on it. Having some problems.

**Comment by frankmorgner** [comment]
@sergioag do you have some update?

**Comment by frankmorgner** [comment]
OK, thanks for trying.
