### PR TITLE
idprime: fix pin padding for SafeNet eToken 5100 [eToken 5110 SC]

### LINKED ISSUE #3488: Invalid pin padding with SafeNet eToken 5100 [eToken 5110 SC] 00 00
I have a SafeNet eToken and when I try to login and list the objects with `pkcs11-tool -L -v -v -O --login` 

I get 
```
Logging in to "Card #15ACEB374F587E43".
Please enter User PIN: 
P:170007; T:0x137025255737344 08:44:21.927 [opensc-pkcs11] pkcs11-session.c:352:C_Login: C_Login(0x5e530cefb2c0, 1)
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] pkcs11-session.c:374:C_Login: C_Login() slot->login_user -1
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] pkcs11-session.c:385:C_Login: C_Login() userType 1
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] framework-pkcs15.c:1815:pkcs15_login: pkcs15-login: userType 0x1, PIN length 6
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] pkcs15-pin.c:304:sc_pkcs15_verify_pin: called
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] pkcs15-pin.c:351:sc_pkcs15_verify_pin_with_session_pin: called
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] pkcs15-pin.c:352:sc_pkcs15_verify_pin_with_session_pin: PIN(type:0; method:1; value(0x5e530cefb360:6)
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] card.c:466:sc_lock: called
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] reader-pcsc.c:717:pcsc_lock: called
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] card.c:505:sc_lock: returning with: 0 (Success)
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] sec.c:203:sc_pin_cmd: called
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] apdu.c:550:sc_transmit_apdu: called
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] card.c:466:sc_lock: called
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] card.c:505:sc_lock: returning with: 0 (Success)
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] apdu.c:515:sc_transmit: called
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] apdu.c:363:sc_single_transmit: called
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] apdu.c:367:sc_single_transmit: CLA:0, INS:20, P1:0, P2:11, data(6) 0x7ffd75c46e70
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] reader-pcsc.c:336:pcsc_transmit: reader 'SafeNet eToken 5100 [eToken 5110 SC] 00 00'
P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] reader-pcsc.c:337:pcsc_transmit: 
Outgoing APDU (11 bytes):
00 20 00 11 06 31 32 33 34 35 36 . ...123456

P:170007; T:0x137025255737344 08:44:21.928 [opensc-pkcs11] reader-pcsc.c:249:pcsc_internal_transmit: called
P:170007; T:0x137025255737344 08:44:21.934 [opensc-pkcs11] reader-pcsc.c:346:pcsc_transmit: 
Incoming APDU (2 bytes):
67 00 g.

P:170007; T:0x137025255737344 08:44:21.934 [opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:170007; T:0x137025255737344 08:44:21.934 [opensc-pkcs11] apdu.c:539:sc_transmit: returning with: 0 (Success)
P:170007; T:0x137025255737344 08:44:21.935 [opensc-pkcs11] card.c:515:sc_unlock: called
P:170007; T:0x137025255737344 08:44:21.935 [opensc-pkcs11] iso7816.c:128:iso7816_check_sw: Wrong length
P:170007; T:0x137025255737344 08:44:21.935 [opensc-pkcs11] sec.c:259:sc_pin_cmd: returning with: -1206 (Wrong length)
P:170007; T:0x137025255737344 08:44:21.935 [opensc-pkcs11] pkcs15-pin.c:443:sc_pkcs15_verify_pin_with_session_pin: PIN cmd result -1206
P:170007; T:0x137025255737344 08:44:21.935 [opensc-pkcs11] card.c:515:sc_unlock: called
P:170007; T:0x137025255737344 08:44:21.935 [opensc-pkcs11] reader-pcsc.c:759:pcsc_unlock: called
P:170007; T:0x137025255737344 08:44:21.935 [opensc-pkcs11] pkcs15-pin.c:465:sc_pkcs15_verify_pin_with_session_pin: returning with: -1206 (Wrong length)
P:170007; T:0x137025255737344 08:44:21.935 [opensc-pkcs11] pkcs15-pin.c:321:sc_pkcs15_verify_pin: returning with: -1206 (Wrong length)
P:170007; T:0x137025255737344 08:44:21.935 [opensc-pkcs11] framework-pkcs15.c:1918:pkcs15_login: PKCS15 verify PIN returned -1206
P:170007; T:0x137025255737344 08:44:21.935 [opensc-pkcs11] misc.c:72:sc_to_cryptoki_error_common: libopensc return value: -1206 (Wrong length)
```
(yes this is a test card with a trivial PIN)

The card works with `safenetauthenticationclient` so I've captured the traffic of a working `PIN_VERIFY` command with `usbmon` and wireshark and it seems like for this card the pin padding length is 16. If I hardcode a padding with 16 in OpenSC, it works.

How can I help to find out where this padding configuration is to be set ? 

USB ID: `0529:0620`
ATR: `3b:ff:96:00:00:81:31:fe:43:80:31:80:65:b0:85:59:56:fb:12:01:78:82:90:00:88 `

### PR DESCRIPTION
**Pull request by hardening**
As reported in https://github.com/OpenSC/OpenSC/issues/3488 , it seems like the `SC_CARD_TYPE_IDPRIME_930_PLUS` cards need padding for the pin.

Tested with a card with ATR `3b:ff:96:00:00:81:31:fe:43:80:31:80:65:b0:85:59:56:fb:12:01:78:82:90:00:88`

Fixes #3488

@metsma it seems like you have a smartcard with almost the same ATR and flagged as `SC_CARD_TYPE_IDPRIME_930_PLUS`, could you check if login works for you with these changes ?

##### Checklist

- [X] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS token is tested

### CODE REVIEW

**Comment by metsma** [comment]
No:

```
Outgoing APDU (21 bytes):
00 20 00 11 10 ** ** ** ** ** ** ** ** 00 00 00
00 00 00 00 00

P:11161; T:0x8292245824 08:48:35.638 [opensc-pkcs11] reader-pcsc.c:249:pcsc_internal_transmit: called
P:11161; T:0x8292245824 08:48:35.679 [opensc-pkcs11] reader-pcsc.c:346:pcsc_transmit: 
Incoming APDU (2 bytes):
63 C4 c?
```

**Comment by Jakuje** [comment]
What I was pointing out in #3488 is that your token is the closes to the `SC_CARD_TYPE_IDPRIME_930_PLUS` token, but clearly not the same as @metsma token does not work with your changes.
This means, you will need to distinguish these two, ideally by the ATR mask.

Please, take a look at the parsed ATR to see meaning of the fields:

https://smartcard-atr.apdu.fr/parse?ATR=3b%3Aff%3A96%3A00%3A00%3A81%3A31%3Afe%3A43%3A80%3A31%3A80%3A65%3Ab0%3A85%3A59%3A56%3Afb%3A12%3A01%3A78%3A82%3A90%3A00%3A88

comparing what is different, its really just the last byte (checksum) and the "pre-issuing data", which is something the vendor can define and interpret on their own (and which will likely encode the version/type of the token/card.

Very similar ATR is also `Gemalto IDPrime MD 940 (eToken 5110)`, but it differs in the "Country code", whatever it should mean for the card. Maybe the solution would be adjusting the mask to the `SC_CARD_TYPE_IDPRIME_940` card by masking the country code ...

sorry for not providing straightforward-solution, but its really a trial and error to get this working ...

**Comment by hardening** [comment]
@Jakuje hum seems like you're right, it also works for me if I adjust masks so that my card is recognized as a `SC_CARD_TYPE_IDPRIME_940`

**Comment by hardening** [comment]
Ok so PR updated, in fact my card works fine when it's identified as a `SC_CARD_TYPE_IDPRIME_940`. I've updated the `IDPRIME_930_PLUS` mask to be more selective, and relaxed the one for `IDPRIME_940`.

File: src/libopensc/card-idprime.c [hunk 1]
```diff
@@ -97,9 +97,10 @@ static const struct sc_atr_table idprime_atrs[] = {
 	  SC_CARD_TYPE_IDPRIME_940, 0, NULL },
 	/* Known ATRs for IDPrime 940 (eToken 5110)
 	 * 3b:ff:96:00:00:81:31:fe:43:80:31:80:65:b0:85:59:56:fb:12:0f:fe:82:90:00:00    metsma, jurajsarinay
+	 * 3b:ff:96:00:00:81:31:fe:43:80:31:80:65:b0:85:59:56:fb:12:01:78:82:90:00:88    hardening
 	 */
 	{ "3b:ff:96:00:00:81:31:fe:43:80:31:80:65:b0:85:59:56:fb:12:0f:fe:82:90:00:00",
-	  "ff:ff:00:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:00:00:00:00:ff:ff:ff:ff:ff:ff:00",
+	  "ff:ff:00:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:00:00:00:00:ff:00:00:ff:ff:ff:00",
```
Comment (frankmorgner) [inline src/libopensc/card-idprime.c]:
```suggestion
	  "ff:ff:00:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:00:00:00:00:ff:f0:00:ff:ff:ff:00",
```

File: src/libopensc/pkcs15-idprime.c
Comment (frankmorgner) [inline src/libopensc/pkcs15-idprime.c:1]: If you only need the ATR change, then please only modify that

Comment (hardening) [reply src/libopensc/pkcs15-idprime.c:1]: ok will drop the change

File: src/libopensc/card-idprime.c (hunk 1 above)
Comment (hardening) [reply src/libopensc/card-idprime.c]: Well I've filtered out all the country code, but I can adjust that so that we take what's common between known ATRs

**Comment by hardening** [comment]
Changes done

**Comment by Jakuje** [comment]
The ubuntu 22 CI jobs are fixed with #3496. I would like to give it a try next week with the cards I have, but otherwise it looks good. I would also like to ask @metsma to have a look if this works with his cards.

**Comment by metsma** [comment]
> The ubuntu 22 CI jobs are fixed with #3496. I would like to give it a try next week with the cards I have, but otherwise it looks good. I would also like to ask @metsma to have a look if this works with his cards.

FIPS+ works, I need to renew certificates to test QSCD token

**Comment by Jakuje** [comment]
Tested this branch with IDprime 3810, 930, 940 and all looks good to me!

File: src/libopensc/card-idprime.c (hunk 1 above)
Comment (frankmorgner) [reply src/libopensc/card-idprime.c]: alright, I didn't notice the semantical change. If you prefer, you may revert this back to your initial proposal to fully ignore the country code

Comment (hardening) [reply src/libopensc/card-idprime.c]: Well I'm not an expert but I've read that the country code may be used as anything that matters for the card. So could be a real country code or something else. So let's adopt your conservative version (the actual PR) that matches the set of known ATRs, we can always relax the mask if some card pops up with another unsupported country code...

**Comment by Jakuje** [comment]
@metsma did you get to renew certs on QSCD and try this or are we good to merge this as it is?

**Comment by metsma** [comment]
> @metsma did you get to renew certs on QSCD and try this or are we good to merge this as it is?

Yes I did and it works and is good to merge

**Comment by Jakuje** [comment]
Thank you for the PR and others for reviews and testing! Merged and rebased.
